IF OBJECT_ID('ACAgedDebtByDay_T', 'U') IS NOT NULL DROP TABLE dbo.ACAgedDebtByDay_T

	
CREATE TABLE [ACAgedDebtByDay_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[dDate] datetime NULL,
	[rShort] float NULL,
	[rMedium] float NULL,
	[rLong] float NULL,
	[rLongPlus] float NULL,
	[rTotal] float NULL,
	[FKiACPolicyID] INT NULL,
	[refAgedDebtCategoryID] INT NULL,
	[refAgedFinanceCategoryID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[refAccountCategory] INT NULL,
	[iShort] INT NULL,
	[iMedium] INT NULL,
	[iLong] INT NULL,
	[iLongPlus] INT NULL,
	[FKiClientID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiEnterpriseID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)