IF OBJECT_ID('ACJournalEntry_T', 'U') IS NOT NULL DROP TABLE dbo.ACJournalEntry_T

	
CREATE TABLE [ACJournalEntry_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[zXCrtdBy] VARCHAR(64) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(64) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiTransTypeID] INT NULL,
	[dtWhen] datetime NULL,
	[dDate] datetime NULL,
	[FKsUserID] VARCHAR(50) NULL,
	[FKiAccountID] INT NULL,
	[rAmount] float NULL,
	[FKiTwinJEID] INT NULL,
	[FKiJETemplateID] INT NULL,
	[FKiTransactionID] INT NULL,
	[rReconciled] float NULL,
	[FKiEnterpriseID] INT NULL,
	[iReconciled] INT NULL,
	[iReconcilliationType] INT NULL,
	[FKiACPolicyID] INT NULL,
	[iTransType] INT NULL,
	[FKiNominalAccID] INT NULL,
	[FKiMonthEndID] INT NULL,
	[refAccountCategory] INT NULL,
	[refControlSectionID] VARCHAR(30) NULL,
	[rSignAmount] float NULL,
	[rCR] float NULL,
	[rDR] float NULL,
	[sWho] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)