IF OBJECT_ID('ACPFApplication_T', 'U') IS NOT NULL DROP TABLE dbo.ACPFApplication_T

	
CREATE TABLE [ACPFApplication_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL default((0)),
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[sFirstName] VARCHAR(50) NULL,
	[sLastName] VARCHAR(50) NULL,
	[sPostCode] VARCHAR(50) NULL,
	[enumTitleID] INT NULL,
	[dDOB] datetime NULL,
	[iEmployed] INT NULL,
	[sAdd1] VARCHAR(80) NULL,
	[sAdd2] VARCHAR(80) NULL,
	[sAdd3] VARCHAR(80) NULL,
	[sAdd4] VARCHAR(80) NULL,
	[sAdd5] VARCHAR(80) NULL,
	[sTelH] VARCHAR(50) NULL,
	[sTelW] VARCHAR(50) NULL,
	[iBankAccNo] VARCHAR(12) NULL,
	[sBankAccName] VARCHAR(100) NULL,
	[iSortCode1] VARCHAR(9) NULL,
	[iSortCode2] VARCHAR(9) NULL,
	[iSortCode3] VARCHAR(9) NULL,
	[sBankName] VARCHAR(100) NULL,
	[sBankBranch] VARCHAR(100) NULL,
	[sBankAdd1] VARCHAR(80) NULL,
	[sBankAdd2] VARCHAR(80) NULL,
	[sBankAdd3] VARCHAR(80) NULL,
	[sBankAdd4] VARCHAR(80) NULL,
	[sBankAdd5] VARCHAR(80) NULL,
	[sBankPostCode] VARCHAR(50) NULL,
	[rPFAmount] float NULL,
	[FKiSupplierID] INT NULL,
	[FKiPFSchemeID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiClientID] INT NULL,
	[rSumTotalPremium] float NULL,
	[rSumDepositAmount] float NULL,
	[rSumInterestPayable] float NULL,
	[rSumInterestRate] float NULL,
	[rSumInstallmentAmount] float NULL,
	[rSumTotalPayable] float NULL,
	[dSumPaymentDate] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[rSumTotalPayableToPFCo] float NULL,
	[d1stPayCollect] datetime NULL,
	[rTotalFinance] float NULL,
	[sSupplierPFAgreementNo] VARCHAR(50) NULL,
	[sSupplierPFAccountNo] VARCHAR(50) NULL,
	[sSumChanges] VARCHAR(4000) NULL,
	[sTypeCode] VARCHAR(20) NULL,
	[sEMail] VARCHAR(80) NULL,
	[rPFCharge] float NULL,
	[sMob] VARCHAR(20) NULL,
	[sRequestObject] VARCHAR(MAX) NULL,
	[sResponseObject] VARCHAR(MAX) NULL,
	[sPartnerTransactionToken] VARCHAR(128) NULL,
	[sPdffilepath] VARCHAR(256) NULL,
	[iResponseType] INT NULL,
	[dDateProcessed] datetime NULL,
	[sTitle] VARCHAR(50) NULL,
	[sPolicyNo] VARCHAR(64) NULL,
	[sBrokerReference] VARCHAR(25) NULL,
	[sPaymentDay] VARCHAR(64) NULL,
	[sFormattedPaymentDay] VARCHAR(64) NULL,
	[iMTAType] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)