IF OBJECT_ID('ACPolicyVersion_T', 'U') IS NOT NULL DROP TABLE dbo.ACPolicyVersion_T

	
CREATE TABLE [ACPolicyVersion_T]
(
	[ID] bigint NOT NULL,
	[FKiACPolicyID] INT NULL,
	[FKiProductVersionID] INT NULL,
	[FKiQSInstanceID] INT NULL,
	[FKiUserID] INT NOT NULL default((0)),
	[zXCrtdBy] VARCHAR(120) NULL,
	[zXCrtdWhn] datetime NOT NULL default(getdate()),
	[zXUpdtdBy] VARCHAR(120) NULL,
	[zXUpdtdWhn] datetime NOT NULL default(getdate()),
	[izXDeleted] INT NULL default((0)),
	[dEffectiveFrom] datetime NULL,
	[dEffectiveTo] datetime NULL,
	[rMTACost] float NULL,
	[iStatus] INT NULL,
	[iPolicyStatus] INT NULL,
	[FKiQuoteID] INT NULL,
	[rGrossPremium] float NULL,
	[rNetPremium] float NULL,
	[rBalance] float NULL,
	[rTotalPremium] float NULL,
	[bIsWithoutPayment] bit NULL default((0)),
	[sReason] VARCHAR(250) NULL,
	[rUsedPremium] float NULL,
	[rPaidAmount] float NULL,
	[sChangeSummary] VARCHAR(250) NULL,
	[sVersion] VARCHAR(120) NULL,
	[rQuotePremium] float NULL,
	[bIsRequirementsGenerated] bit NULL default((0)),
	[bIsDiariesGenerated] bit NULL default((0)),
	[bIsDocumentsGenerated] bit NULL default((0)),
	[bIsTransactionsPosted] bit NULL default((0)),
	[bIsEDIGenerated] bit NULL default((0)),
	[rMTACommission] float NULL,
	[rMTANetToSupplier] float NULL,
	[rMTATax] float NULL,
	[iType] INT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[FKiQSInstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKsUserID] VARCHAR(50) NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[iCreatedWho] int NOT NULL default((0))
)