IF OBJECT_ID('ACPurchase_T', 'U') IS NOT NULL DROP TABLE dbo.ACPurchase_T

	
CREATE TABLE [ACPurchase_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(256) NULL,
	[iStatus] INT NULL default((0)),
	[izXDeleted] INT NULL default((0)),
	[sNotes] VARCHAR(250) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[refAddOn] INT NULL,
	[FKiProductAddonID] INT NULL,
	[dExpires] datetime NULL,
	[rCost] decimal(18,6) NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[FKiClientID] INT NULL,
	[rAdmin] decimal(18,2) NOT NULL default((0)),
	[sAlert] VARCHAR(50) NULL,
	[rPremiumOverride] decimal(18,2) NULL,
	[FKiQSInstanceID] INT NULL,
	[sVerificationCode] VARCHAR(120) NULL,
	[sAddonNo] VARCHAR(120) NULL,
	[bIsConverted] bit NOT NULL default((0)),
	[dCoverStart] datetime NULL,
	[tCoverStart] VARCHAR(50) NULL,
	[dCoverEnd] datetime NULL,
	[tCoverEnd] VARCHAR(50) NULL,
	[sSupplierID] VARCHAR(128) NULL,
	[FKsPolicyNo] VARCHAR(128) NULL,
	[FKsClientReferenceNumber] VARCHAR(128) NULL,
	[FKiSupplierID] INT NULL,
	[bIsAddonQS] bit NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiQuoteID] INT NULL,
	[FKiProductVersionID] INT NULL,
	[FKiQSInstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[rAddonTotal] decimal(18,2) NULL,
	[iQuantity] int NOT NULL DEFAULT((0))
)