IF OBJECT_ID('ACReconcilliation_T', 'U') IS NOT NULL DROP TABLE dbo.ACReconcilliation_T

	
CREATE TABLE [ACReconcilliation_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(128) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiEnterpriseID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[dtPosted] datetime NULL,
	[FKsUserID] VARCHAR(64) NULL,
	[sHTMLResult] VARCHAR(4000) NULL,
	[sActRec] VARCHAR(50) NULL,
	[sChequeNo] VARCHAR(50) NULL,
	[rTotalPremium] float NULL,
	[rTotalIPT] float NULL,
	[rTotalCommission] float NULL,
	[rTotalNet] float NULL,
	[rTotalPaid] float NULL,
	[rTotalAdjustments] float NULL,
	[FKiACTransactionID] INT NULL,
	[sReference] VARCHAR(50) NULL,
	[iOpenDRCR] INT NULL,
	[iCloseDRCR] INT NULL,
	[rOpeningBalance] float NULL,
	[rClosingBalance] float NULL,
	[iDirection] INT NULL,
	[refAccountCategory] INT NULL,
	[dPostingDate] datetime NULL,
	[FKiAccountOverrideID] INT NULL,
	[FKiBrokerID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)