IF OBJECT_ID('ACTransType_T', 'U') IS NOT NULL DROP TABLE dbo.ACTransType_T

	
CREATE TABLE [ACTransType_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(255) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(255) NULL,
	[sAlert] VARCHAR(255) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[zXCrtdBy] VARCHAR(255) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(255) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiCRAccountID] INT NULL,
	[FKiDRAccountID] INT NULL,
	[sCRAccount] VARCHAR(255) NULL,
	[sDRAccount] VARCHAR(255) NULL,
	[bProRata] bit NULL,
	[bReverse] bit NULL,
	[bAllocatedTransaction] bit NULL,
	[sCode] VARCHAR(255) NULL,
	[bPolicy] bit NULL,
	[bClient] bit NULL,
	[bAccounts] bit NULL,
	[bSupplier] bit NULL,
	[bPF] bit NULL,
	[bAllocatedTo] bit NULL,
	[bIPT] bit NULL,
	[bBusinessWritten] bit NULL,
	[sGroupOverride] VARCHAR(255) NULL,
	[sOpposingTransCode] VARCHAR(255) NULL,
	[FKiSysApplicationID] INT NULL,
	[iAccountsSet] INT NULL,
	[bPurchase] bit NULL,
	[bCommission] bit NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)