IF OBJECT_ID('ACTransaction_T', 'U') IS NOT NULL DROP TABLE dbo.ACTransaction_T

	
CREATE TABLE [ACTransaction_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiACAccountID] INT NULL,
	[FKiACTransTypeID] INT NULL,
	[zXCrtdBy] VARCHAR(64) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(64) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiQuoteID] INT NULL,
	[FKiClientID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiProductID] INT NULL,
	[zCommission] float NULL,
	[iCommissionType] INT NULL,
	[zDefaultAdmin] float NULL,
	[iAdminType] INT NULL,
	[zDefaultDeposit] float NULL,
	[iDepositType] INT NULL,
	[iTaxType] INT NULL,
	[dWhen] datetime NULL,
	[rCommission] float NULL,
	[rAdmin] float NULL,
	[rDeposit] float NULL,
	[rTax] float NULL,
	[zBaseValue] float NULL,
	[FKiACTrans] INT NULL,
	[FKiACPolicyID] INT NULL,
	[rNetToSupplier] float NULL,
	[sAnalysis] text NULL,
	[rIncome] float NULL,
	[FKiSourceID] INT NULL,
	[FKiCRAccountID] INT NULL,
	[FKiDRAccountID] INT NULL,
	[iDays] INT NULL,
	[rBalance] float NULL,
	[sPFNo] VARCHAR(100) NULL,
	[FKiPFSchemeID] INT NULL,
	[iProcessStatus] INT NULL,
	[sReference] VARCHAR(50) NULL,
	[sOverrideCode] VARCHAR(50) NULL,
	[dCoverStart] datetime NULL,
	[tCoverStart] VARCHAR(50) NULL,
	[FKiAddOnID] INT NULL,
	[FKiEnterpriseID] INT NULL,
	[rAllocatedAgainst] float NULL,
	[rAllocatedToByOthers] float NULL,
	[iStatutory] INT NULL,
	[iRiskTrnasfer] INT NULL,
	[iEDIStatus] INT NULL,
	[iPaymentType] INT NULL,
	[sTransCode] VARCHAR(100) NULL,
	[FKiACPolicyAllocID] INT NULL,
	[rPremium] float NULL,
	[FKiMonthEndID] INT NULL,
	[bBusinessWritten] bit NULL,
	[rCommAdj] float NULL,
	[refAnalysis1] INT NULL,
	[refTypeID] INT NULL,
	[iSystemType] INT NULL,
	[sPolTransCode] VARCHAR(100) NULL,
	[dProcessDate] datetime NULL,
	[sFeedback] VARCHAR(250) NULL,
	[sChequeNo] VARCHAR(50) NULL,
	[iAllocPriority] INT NULL,
	[iPostedFrom] INT NULL,
	[rComOverride] VARCHAR(50) NULL,
	[refAccountCategory] INT NULL,
	[iPFRec] INT NULL,
	[refControlSectionID] VARCHAR(30) NULL,
	[sManagerCodeEncrypt] VARCHAR(50) NULL,
	[sManagerCode] VARCHAR(50) NULL,
	[iCodeType] INT NULL,
	[iBatchID] INT NULL,
	[iSystem] INT NULL,
	[sReconciliationHistory] VARCHAR(250) NULL,
	[FKiProductAddOnID] INT NULL,
	[rSignAmount] float NULL,
	[FKiSysApplicationID] INT NULL,
	[FKiBrokerID] INT NULL,
	[FKiPurchaseID] INT NULL,
	[FKsWhoID] VARCHAR(50) NULL,
	[iTransType] INT NULL,
	[FKsPolicyNo] VARCHAR(64) NULL,
	[sWho] VARCHAR(256) NULL,
	[FKiPolicyVersionID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)