IF OBJECT_ID('Aggregations_T', 'U') IS NOT NULL DROP TABLE dbo.Aggregations_T

	
CREATE TABLE [Aggregations_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sInsurer] VARCHAR(512) NULL default('Insurer'),
	[rPrice] float NULL,
	[FKiQSInstanceID] INT NULL,
	[FKiCustomerID] INT NULL,
	[FKiUserID] INT NULL,
	[CreatedTime] datetime NULL,
	[FKiProductVersionID] INT NULL,
	[MTArPrice] float NULL,
	[DELTArPrice] float NULL,
	[MTAEffectiveDate] datetime NULL,
	[MTAiStatus] INT NULL,
	[BatchID] varchar(256) NULL,
	[iStatus] INT NULL default((0)),
	[izXDeleted] INT NULL default((0)),
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[zDefaultAdmin] float NULL,
	[zDefaultDeposit] float NULL,
	[rAddonPrice] float NULL default((0.00)),
	[rTotal] float NULL default((0.00)),
	[rPremiumFinanceAmount] float NULL,
	[rFinalQuote] float NULL default((0)),
	[sVerificationCode] VARCHAR(120) NULL,
	[sGUID] VARCHAR(128) NULL,
	[sRefID] VARCHAR(128) NULL,
	[iTerm] INT NULL,
	[rMonthlyPrice] float NULL,
	[sExcess] VARCHAR(MAX) NULL,
	[bIsCoverAbroad] bit NULL default((0)),
	[rAddonAdmin] float NULL default((0.00)),
	[rTotalAdmin] float NULL default((0.00)),
	[rPaymentCharge] float NULL default((0.00)),
	[rInsurerCharge] float NULL default((0.00)),
	[iQuoteStatus] INT NULL default((0)),
	[rMonthlyTotal] float NULL,
	[rCompulsoryExcess] float NULL,
	[rFinalPremium] float NULL,
	[rVoluntaryExcess] float NULL,
	[rTotalExcess] float NULL,
	[rGrossPremium] float NULL,
	[iBuyStatus] INT NULL default((0)),
	[sRegNo] VARCHAR(20) NULL,
	[dCoverStart] datetime NULL,
	[sCaravanMake] VARCHAR(250) NULL,
	[sCaravanModel] VARCHAR(250) NULL,
	[sExternalRefID] VARCHAR(512) NULL,
	[sTypeOfCover] VARCHAR(250) NULL,
	[iPaymentType] INT NULL,
	[rInterestAmount] float NULL,
	[rInterestRate] float NULL,
	[rPayableAmount] float NULL,
	[sAddonDescription] VARCHAR(250) NULL,
	[FKiPFSchemeID] INT NULL,
	[sName] VARCHAR(512) NULL,
	[FKsPolicyNo] VARCHAR(120) NULL,
	[sInsurerRefCode] VARCHAR(120) NULL,
	[sSummaryContent] VARCHAR(MAX) NULL,
	[dtQSUpdatedDate] datetime NULL,
	[iQSType] INT NULL,
	[bIsVisibleToUser] bit NULL default((0)),
	[rQuotePremium] float NULL,
	[rSubTotal] float NULL,
	[iRank] INT NULL,
	[iOverallStatus] INT NULL,
	[bIsOverRide] bit NULL,
	[zCommission] float NULL,
	[iCommissionType] INT NULL,
	[FKiLeadID] INT NULL,
	[rExcLegalNIPT] float NULL,
	[rLegal] float NULL,
	[FKiClassID] INT NULL default((1)),
	[iType] INT NOT NULL default((10)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[rDefaultQuotePrice] float NULL default((0.0)),
	[bIsFlood] bit NULL default((0)),
	[bIsApplyFlood] bit NULL default((0)),
	[FKiOrgID] INT NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[iButtonType] INT NULL,
	[FKiInsurerID] bigint NULL,
	[iQuoteType] INT NOT NULL default((0)),
	[FKizXDoc] VARCHAR(250) NULL,
	[bIsRecommended] bit NULL,
	[bIsRenewExternalQuote] bit NULL,
	[iDeclineReason] int NULL,
	[sDeclineReason] varchar(128) NULL ,
	[sAllowedValue] nvarchar(256) NULL ,
	[rCommission] float NOT NULL DEFAULT((0)) ,
	[rCommissionRebate] float NULL DEFAULT((0)),
	[rAdjustedCommission] float NULL DEFAULT((0)),
	[zCommissionOverride] float NULL ,
	[rAdmin] float NOT NULL DEFAULT((0)) ,
	[rOverrideAdmin] float NOT NULL DEFAULT((0)) ,
	[rPaymentToInsurer] float NULL ,
	[bISConfirmPolicy] bit NULL ,
	[sCode] varchar(8) NULL ,
	[sOverrideCommissionRebate] float NULL ,
	[bISPaymentToInsurer] bit NULL ,
	[FKiSubQSInstanceID] int NULL ,
	[bIsAllowDirectToInsurer] bit NULL ,
	[bIsPayInInstallments] bit NULL ,
	[rInstallmentInterestRate] float NULL ,
	[rCost] float NULL ,
	[rFinalCommission] float NOT NULL DEFAULT((0)),
	[iPaymentMethodType] int NULL,
	[FKiQSInstanceIDXIGUID] uniqueidentifier NULL,
	[FKiMTAQSInstanceID] int NULL,
	[FKiRiskQSIIDXIGUID] uniqueidentifier NOT NULL DEFAULT('00000000-0000-0000-0000-000000000000'),
	[FKiMTAQSInstanceIDXIGUID] uniqueidentifier NOT NULL DEFAULT('00000000-0000-0000-0000-000000000000'),
	[FKiSubQSInstanceIDXIGUID] uniqueidentifier NOT NULL DEFAULT('00000000-0000-0000-0000-000000000000'),
	[sGroupQuote] varchar(MAX) NULL,
	[bIsAppliedPostScript] bit NULL,
	[fPercentComplete] float NOT NULL DEFAULT((0)),
	[sAdditionalNotes] varchar(MAX) NULL,
	[bIsProceedCover] bit NOT NULL default((0)),
	[iCreatedWho] int NOT NULL default((0)),
	[rHalfPayAmount] Float not null default((0)),
	[rFinancialAmount] Float not null default((0)),
	[rFinancialPendingAmount] Float not null default((0)),
	[rIPT] float NULL,
	[rIPTValue] float NULL,
	[rDeposit] float NULL,
	[iPaymentTypeforNW] int NULL,
	[sAccountHolderforNW] varchar(64) NULL,
	[iAccountNumberforNW] varchar(256) NULL,
	[iSortCodeforNW] int NULL,
	[sBankNameforNW] varchar(256) NULL,
	[rTotalDue] float NULL,
)