IF OBJECT_ID('Call_T', 'U') IS NOT NULL DROP TABLE dbo.Call_T

	
CREATE TABLE [Call_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(MAX) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] NVARCHAR(MAX) NULL,
	[sAlert] NVARCHAR(50) NULL,
	[sLogo] NVARCHAR(50) NULL,
	[sCallDesc] ntext NULL,
	[dWhen] smalldatetime NULL,
	[nCallType] INT NULL,
	[sFollowUpDetails] NVARCHAR(250) NULL,
	[dFollowUpDate] smalldatetime NULL,
	[sFollowUpWho] NVARCHAR(50) NULL,
	[dFollowUpDoneDate] smalldatetime NULL,
	[sFollowUpResult] NVARCHAR(250) NULL,
	[refCallAbout] INT NULL,
	[sThread] NVARCHAR(50) NULL,
	[FKiContactID] INT NULL,
	[FKiCustomerID] INT NULL,
	[FKiOrderID] INT NULL,
	[FKiSupplierID] INT NULL,
	[iType] INT NULL,
	[FKizxDocID] INT NULL,
	[iDocumentStatus] INT NULL,
	[FKsPrinterID] NVARCHAR(25) NULL,
	[iNoOfCopies] INT NULL,
	[FKiDocumentTemplateID] INT NULL,
	[FKsRecordedID] NVARCHAR(50) NULL,
	[FKiHTMLTemplateID] INT NULL,
	[FKiSupplierContactID] INT NULL,
	[FKiQuoteID] INT NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[FKiCampaignInstanceID] INT NULL,
	[sEMail] NVARCHAR(50) NULL,
	[sWho] NVARCHAR(100) NULL,
	[FKiTaskID] INT NULL,
	[FKiProductID] INT NULL,
	[FKiACPolicyID] INT NULL,
	[iDirection] INT NULL,
	[sErrorMessage] VARCHAR(250) NULL,
	[refCallTypeID] INT NULL,
	[FKiReminderID] INT NULL,
	[iAction] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiRequirementID] INT NULL,
	[iAdvanceStatus] INT NULL,
	[FKiAMPhaseStepID] INT NULL,
	[refAMCategory] INT NULL,
	[sEMailedTo] VARCHAR(4000) NULL,
	[FKizxDocPDFID] INT NULL,
	[sAMCatAsString] VARCHAR(50) NULL,
	[FKiCurrentTraceID] INT NULL,
	[iHotStatus] INT NULL,
	[FKi1ClickID] INT NULL,
	[FKiLeadID] INT NULL,
	[FKiMergeEmailContentID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiClaimID] INT NULL,
	[iTypeOfCommunication] INT NULL,
	[iHandler] INT NULL,
	[FKiCompliantsID] INT NULL,
	[FKiComplaintID] INT NULL,
	[FKiCommIID] INT NULL,
	[FKiCommIIDXIGUID] UNIQUEIDENTIFIER NULL,
	[iActionStatus] INT NULL
)