IF OBJECT_ID('CancelPolicy_T', 'U') IS NOT NULL DROP TABLE dbo.CancelPolicy_T

	
CREATE TABLE [CancelPolicy_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[iCancelWho] INT NULL,
	[refCancelReason] INT NULL,
	[bDocumentsReceived] bit NULL,
	[bNoClaims] bit NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiCPolicyCalcID] INT NULL,
	[rCancelRate] float NULL,
	[iCancelReason10] INT NULL,
	[iCancelReason20] INT NULL,
	[iCancelReason30] INT NULL,
	[rCancellationFee] float NULL,
	[FKiACPolicyID] INT NULL,
	[rCancelRateManual] float NULL,
	[dDate] datetime NULL,
	[dInsurerCallDate] datetime NULL,
	[tInsurerCallTime] VARCHAR(8) NULL,
	[sInsurerContact] VARCHAR(50) NULL,
	[sInsurerReference] VARCHAR(50) NULL,
	[FKsUserID] VARCHAR(20) NULL,
	[sTime] VARCHAR(10) NULL,
	[FKsPolicyNo] VARCHAR(120) NULL,
	[sDeclineReason] VARCHAR(MAX) NULL,
	[FKiAddonID] INT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sClientOtherReason] VARCHAR(50) NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)