IF OBJECT_ID('ClaimMidTerm_T', 'U') IS NOT NULL DROP TABLE dbo.ClaimMidTerm_T

	
CREATE TABLE [ClaimMidTerm_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[refClaimTypeID] INT NULL,
	[dDate] datetime NULL,
	[bPersonalInjury] bit NULL,
	[rCostOwn] float NULL,
	[rCost3rdParty] float NULL,
	[rCostInjured] float NULL,
	[rTotalClaimCost] float NULL,
	[iNCDLost] INT NULL,
	[sClaimReference] VARCHAR(50) NULL,
	[sConviction] VARCHAR(50) NULL,
	[iWhoseFault] INT NULL,
	[FKiACPolicyID] INT NULL,
	[FKiClientID] INT NULL,
	[FKiDriverID] INT NULL,
	[iClientClaimID] INT NULL,
	[iOriginal] INT NULL,
	[sClaimTypeDesc] VARCHAR(50) NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKsPolicyNo] VARCHAR(120) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)