IF OBJECT_ID('Claim_T', 'U') IS NOT NULL DROP TABLE dbo.Claim_T

	
CREATE TABLE [Claim_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[dDate] datetime NULL,
	[rCostOwn] float NULL,
	[rCost3rdParty] float NULL,
	[rCostInjured] float NULL,
	[rTotalClaimCost] float NULL,
	[iNCDLost] INT NULL,
	[sClaimReference] VARCHAR(50) NULL,
	[sConviction] VARCHAR(50) NULL,
	[iWhoseFault] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[FKiClientID] INT NULL,
	[refClaimTypeID] INT NULL,
	[bPersonalInjury] bit NULL,
	[FKiDriverID] INT NULL,
	[iClientClaimID] INT NULL,
	[iOriginal] INT NULL,
	[sClaimTypeDesc] VARCHAR(50) NULL,
	[iClaimsSection] INT NULL,
	[enumTypeOfLoss] INT NULL,
	[iClaimMade] INT NULL,
	[iSettled] INT NULL,
	[rHTotalClaimCost] float NULL,
	[bPupilDriving] bit NULL,
	[iOnPolicyOfProposer] INT NULL,
	[iAccidentType] INT NULL,
	[FKiPolicyVersionID] INT NULL,
	[FKiQSInstanceID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[rEstimatedValue] float NULL,
	[iHandler] INT NULL,
	[sCover] INT NULL,
	[sDetails] VARCHAR(256) NULL,
	[FKiClaimID] INT NULL,
	[FkiQSinstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiDriverIDXIGUID] uniqueidentifier NULL
)