IF OBJECT_ID('CommunicationInstance_T', 'U') IS NOT NULL DROP TABLE dbo.CommunicationInstance_T

	
CREATE TABLE [CommunicationInstance_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sFrom] NVARCHAR(125) NOT NULL,
	[sTo] NVARCHAR(125) NOT NULL,
	[iType] INT NOT NULL default((0)),
	[sReference] NVARCHAR(250) NULL,
	[FKiToContactID] INT NOT NULL default((0)),
	[sDirection] NVARCHAR(10) NULL,
	[iRetryCount] INT NOT NULL default((0)),
	[sAPI] NVARCHAR(500) NULL,
	[iStatus] INT NOT NULL default((0)),
	[iDeliveryStatus] INT NOT NULL default((0)),
	[iInteractionStatus] INT NOT NULL default((0)),
	[CreatedDate] datetime NOT NULL default(getdate()),
	[OpenDT] datetime NULL,
	[ReadDateDT] datetime NULL,
	[ClickedDT] datetime NULL,
	[RepliedDT] datetime NULL,
	[FKiTaskID] INT NOT NULL default((0)),
	[iErrorCode] INT NULL default((0)),
	[sErrorMessage] NVARCHAR(MAX) NULL,
	[bIsOpened] bit NOT NULL default((0)),
	[bIsReminder] bit NOT NULL default((0)),
	[ReminderDT] datetime NULL,
	[FKiReminderID] VARCHAR(125) NULL,
	[FKiBODID] INT NOT NULL default((0)),
	[FKiBOIID] INT NOT NULL default((0)),
	[sFullMessageID] VARCHAR(250) NULL,
	[sName] VARCHAR(256) NULL,
	[sDescription] VARCHAR(256) NULL,
	[sCode] VARCHAR(256) NULL,
	[XICreatedBy] VARCHAR(15) Not NULL,
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedBy] VARCHAR(15) Not NULL,
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[XIDeleted] INT NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[FKiCampaignID] INT NULL,
	[FKiLeadID] INT NULL
)