IF OBJECT_ID('ConversationI_T', 'U') IS NOT NULL DROP TABLE dbo.ConversationI_T

	
CREATE TABLE [ConversationI_T]
(
	[sAlias1] VARCHAR(256) NULL,
	[XICreatedBy] VARCHAR(15) Not NULL,
	[XICreatedWhen] datetime NOT NULL,
	[XIUpdatedBy] VARCHAR(15) Not NULL,
	[XIUpdatedWhen] datetime NOT NULL,
	[XIDeleted] INT NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sAlias2] VARCHAR(256) NULL,
	[sAlias3] VARCHAR(256) NULL,
	[sAlias4] VARCHAR(256) NULL,
	[sAlias5] VARCHAR(256) NULL,
	[FKiDef1ID] VARCHAR(128) NULL,
	[FKiInst1ID] VARCHAR(128) NULL,
	[FKiDef2ID] VARCHAR(128) NULL,
	[FKiInst2ID] VARCHAR(128) NULL,
	[FKiDef3ID] VARCHAR(128) NULL,
	[FKiInst3ID] VARCHAR(128) NULL,
	[FKiDef4ID] VARCHAR(128) NULL,
	[FKiInst4ID] VARCHAR(128) NULL,
	[FKiDef5ID] VARCHAR(128) NULL,
	[FKiInst5ID] VARCHAR(128) NULL,
	[sName] VARCHAR(256) NULL,
	[sDescription] VARCHAR(256) NULL,
	[sCode] VARCHAR(256) NULL,
	[ID] INT NULL
)