IF OBJECT_ID('Conviction_T', 'U') IS NOT NULL DROP TABLE dbo.Conviction_T

	
CREATE TABLE [Conviction_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FKiDocumentID] INT NULL,
	[sName] VARCHAR(100) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[sLogo] VARCHAR(50) NULL,
	[dDate] datetime NULL,
	[refConviction] INT NULL,
	[FKiQuoteID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[FKiDriverID] INT NULL,
	[rClaimOnPolicy] float NULL,
	[rCostOwn] float NULL,
	[rCost3rdParty] float NULL,
	[rCostInjured] float NULL,
	[iNCDLost] INT NULL,
	[iWhoseFault] INT NULL,
	[sPending] VARCHAR(50) NULL,
	[sAlcoholLevelType] VARCHAR(50) NULL,
	[rFine] float NULL,
	[iPenaltyPoints] INT NULL,
	[sLengthOfSuspension] INT NULL,
	[sProsecutionPending] VARCHAR(50) NULL,
	[iType] INT NULL,
	[dIncidentDate] datetime NULL,
	[iOriginal] INT NULL,
	[iLinkedToFaultClaim] INT NULL,
	[sCode] VARCHAR(10) NULL,
	[sCodeType] VARCHAR(10) NULL,
	[FKiPolicyVersionID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiDriverIDXIGUID] uniqueidentifier NULL
)