IF OBJECT_ID('Customer_T', 'U') IS NOT NULL DROP TABLE dbo.Customer_T

	
CREATE TABLE [Customer_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(60) NULL,
	[sMobileNo] VARCHAR(32) NULL,
	[sCity] VARCHAR(50) NULL,
	[sAge] INT NULL,
	[FKiLocationID] INT NULL default((0)),
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] NVARCHAR(250) NULL,
	[sAlert] NVARCHAR(50) NULL,
	[sExtID] NVARCHAR(50) NULL,
	[sAccNo] NVARCHAR(50) NULL,
	[sExtKey] NVARCHAR(50) NULL,
	[sType] NVARCHAR(40) NULL,
	[sSex] NVARCHAR(5) NULL,
	[sSalutation] NVARCHAR(50) NULL,
	[sForename1] VARCHAR(60) NULL,
	[sForename2] NVARCHAR(50) NULL,
	[sSurname] VARCHAR(60) NULL,
	[sTel1] NVARCHAR(50) NULL,
	[sTel2] NVARCHAR(50) NULL,
	[refSource] INT NULL,
	[sReference] NVARCHAR(50) NULL,
	[dCreated] smalldatetime NULL,
	[sStatus] NVARCHAR(5) NULL,
	[sEmail] NVARCHAR(50) NULL,
	[sFax] NVARCHAR(50) NULL,
	[sMob] NVARCHAR(50) NULL,
	[sAgentCode] NVARCHAR(50) NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[FKiImportQuoteID] INT NULL,
	[add_id] INT NULL,
	[add_address1] NVARCHAR(40) NULL,
	[add_address2] NVARCHAR(40) NULL,
	[add_address3] NVARCHAR(40) NULL,
	[add_address4] NVARCHAR(40) NULL,
	[add_postcode] NVARCHAR(10) NULL,
	[FKiACAccountID] INT NULL,
	[FKiSourceID] INT NULL,
	[dDOBYoungest] datetime NULL,
	[iVehiclesInFamily] INT NULL,
	[sOtherInsurance] VARCHAR(50) NULL,
	[sPreviousInsurer] VARCHAR(50) NULL,
	[iCompanyCar] INT NULL,
	[FKsUserID] VARCHAR(50) NULL,
	[dDOB] datetime NULL,
	[sMaidenName] VARCHAR(100) NULL,
	[sLandLineSupplier] VARCHAR(100) NULL,
	[sNationality] VARCHAR(100) NULL,
	[bPermanentUK] bit NULL,
	[bSmoker] bit NULL,
	[iDrivingLicence] INT NULL,
	[iPointsOnLicence] INT NULL,
	[bMotoringConvictions] bit NULL,
	[bHadRecentMotorAccident] bit NULL,
	[FKiDataInID] INT NULL,
	[iMaritalStatus] INT NULL,
	[sExternalRef] VARCHAR(50) NULL,
	[iResidentialStatus] INT NULL,
	[FKiDataTransactionID] INT NULL,
	[enumTitleID] INT NULL,
	[iRequirementFollowUp] INT NULL,
	[dLastFollowup] datetime NULL,
	[iContactMethod] INT NULL,
	[sCorrespondanceAddress] VARCHAR(250) NULL,
	[sCorrespondancePostcode] VARCHAR(10) NULL,
	[iLivePolicyCount] INT NULL default((0)),
	[FKiUserID] INT NULL,
	[bDisableClientLogin] bit NULL,
	[sExternalRefID] VARCHAR(512) NULL,
	[bIsMailSended] bit NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[FKiOrgID] bit NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[iDateType] INT NULL,
	[sClientType] INT NULL,
	[FKiBrandID] bigint NULL,
	[sDescription] varchar(256) NULL,
	[sCode] varchar(256) NULL,
	[iType] int NULL,
	[sHierarchy] varchar(256) NULL
)