IF OBJECT_ID('DocumentTemplate', 'U') IS NOT NULL DROP TABLE dbo.DocumentTemplate

	
CREATE TABLE [DocumentTemplate]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] NVARCHAR(100) NULL,
	[sDescription] ntext NULL,
	[bForCustomer] bit NULL,
	[bForSupplier] bit NULL,
	[bForIntroducer] bit NULL,
	[iCaseType] INT NULL,
	[sDocumentTemplate] NVARCHAR(100) NULL,
	[bRequiresSubject] bit NULL,
	[sDefaultSubject] ntext NULL,
	[bRequiresBody] bit NULL,
	[sDefaultBody] ntext NULL,
	[sDefaultCallSummary] ntext NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[iType] INT NULL,
	[sSystemTemplate] NVARCHAR(50) NULL,
	[sPath] NVARCHAR(50) NULL,
	[izXDeleted] INT NULL,
	[refTypeID] INT NULL,
	[refTCategoryID] INT NULL,
	[iTeleType] INT NULL,
	[sCode] VARCHAR(30) NULL,
	[iUsage] INT NULL,
	[iStatus] INT NULL,
	[iPolicyProcess] INT NULL,
	[iMerge] INT NULL,
	[FKiProductID] INT NULL,
	[FKiProductAddonID] INT NULL,
	[sCallAttributeName] VARCHAR(50) NULL,
	[sCallAttributeValue] VARCHAR(50) NULL,
	[sEMailFrom] VARCHAR(80) NULL,
	[sSMSFromNo] VARCHAR(30) NULL,
	[FKiTemplateID] INT NULL,
	[sCopyDocumentName] VARCHAR(80) NULL,
	[iTransactionType] INT NULL,
	[bIsGenerate] bit NULL default((0)),
	[sWhenGenerate] VARCHAR(50) NULL,
	[bIsDocumentCopy] bit NULL,
	[iTemplateType] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[FKiClassID] INT NOT NULL default((0)),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FkiExternalTemplateID] bigint NULL,
	[FKiProductVersionID] bigint NULL,
	[FKiTemplateIDXIGUID] uniqueidentifier NULL
)