IF OBJECT_ID('Documents_T', 'U') IS NOT NULL DROP TABLE dbo.Documents_T

	
CREATE TABLE [Documents_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FileName] VARCHAR(MAX) NULL,
	[FKiDocType] INT NULL,
	[SubDirectoryPath] VARCHAR(128) NULL,
	[iSystemgeneratedorUploaded] INT NULL,
	[sFullPath] VARCHAR(1024) NULL,
	[iInstanceID] INT NULL,
	[FKiUserID] INT NOT NULL default((0)),
	[dCreatedTime] datetime NULL,
	[dUpdatedTime] datetime NULL,
	[iCreatedBy] INT NULL,
	[iUpdatedBy] INT NULL,
	[sCreatedBySYSID] VARCHAR(64) NULL,
	[sUpdatedBySYSID] VARCHAR(64) NULL,
	[sAliasName] VARCHAR(1024) NULL,
	[zXCrtdBy] VARCHAR(120) NULL,
	[zXCrtdWhn] datetime NOT NULL default(getdate()),
	[zXUpdtdBy] VARCHAR(120) NULL,
	[zXUpdtdWhn] datetime NOT NULL default(getdate()),
	[izXDeleted] INT NULL default((0)),
	[iType] INT NOT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER null default(newid()),
	[bIsVisibleToUser] bit NULL default((1)),
	[sName] VARCHAR(MAX) NULL,
	[FKiPolicyVersionID] INT NULL,
	[FKiQSInstanceID] INT NULL,
	[FKiBOID] INT NULL,
	[FKiOrgID] INT NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiClaimID] INT NULL,
	[FkiClientID] bigint NOT NULL default((0)),
	[FKiCompliantsID] INT NULL,
	[FKiComplaintID] INT NULL,
	[FKiQSInstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiPolicyID] INT NULL,
	[bSharetoclient] bit NOT NULL DEFAULT((0)),
	[FKiRequiredDocID] INT NULL,
	[bIsSelection] bit NOT NULL DEFAULT((0))
)