IF OBJECT_ID('Driver_T', 'U') IS NOT NULL DROP TABLE dbo.Driver_T

	
CREATE TABLE [Driver_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[zXCrtdWhn] datetime NULL,
	[FKiPolicyID] INT NULL,
	[iAge] INT NULL,
	[dDOB] datetime NULL,
	[iSex] INT NULL,
	[sForeName] VARCHAR(100) NULL,
	[sRelationship] VARCHAR(50) NULL,
	[iMaritalStatus] INT NULL,
	[sUKResidency] datetime NULL,
	[sLifestyle] VARCHAR(50) NULL,
	[sCommutingExtent] VARCHAR(50) NULL,
	[iLicenceType] INT NULL,
	[dDateTestPassed] datetime NULL,
	[dDateLicenceAquired] datetime NULL,
	[sDrivingQualification] VARCHAR(50) NULL,
	[dQualification] datetime NULL,
	[iNoOtherVehicles] INT NULL,
	[sNCDOnOtherVehicle] VARCHAR(50) NULL,
	[iNoOtherVehAccess] INT NULL,
	[enumProfessionMainID] INT NULL,
	[enumBusinessID] INT NULL,
	[sMainEmployStatus] VARCHAR(50) NULL,
	[enumProfessionPTID] INT NULL,
	[sSecondEmpStatus] VARCHAR(50) NULL,
	[enumTitleID] INT NULL,
	[enumRelationship] INT NULL,
	[enumLicenceTypeID] INT NULL,
	[enumMainEmploymentTypeID] INT NULL,
	[enumBusiness2ID] INT NULL,
	[enumPTEmploymentTypeID] INT NULL,
	[iClaims3Years] INT NULL,
	[iConvict5Years] INT NULL,
	[bMedical] bit NULL,
	[bBusinessUse] bit NULL,
	[bMainDriver] bit NULL default((0)),
	[bRatedDriver] bit NULL,
	[bOtherVehicles] bit NULL,
	[FKiClientID] INT NULL,
	[FKiProductID] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[iOriginal] INT NULL,
	[bSDPOnly] bit NULL,
	[iUsage] INT NULL,
	[sAddress] VARCHAR(250) NULL,
	[sPostCode] VARCHAR(50) NULL,
	[bMotorcycleCover] bit NULL,
	[enumMaritalStatus] INT NULL,
	[bBikeLicGt1Year] bit NULL,
	[iInstructorLevel] INT NULL,
	[dQualifiedADI] datetime NULL,
	[iDemeritPoints] INT NULL,
	[iCommuting] INT NULL,
	[rLoad] float NULL,
	[iFullPT_MT] INT NULL,
	[rProfessionLoad] float NULL,
	[rBusinessLoad] float NULL,
	[enumTradeOccupation] INT NULL,
	[bFullTime] bit NULL,
	[bDeceased] bit NULL,
	[sDeceasedDetails] VARCHAR(250) NULL,
	[enumDriverProficiency] INT NULL,
	[rOwnMatrix] float NULL,
	[rOwnAddLoad] float NULL,
	[s2ndOccNoABU] VARCHAR(100) NULL,
	[sEMail] VARCHAR(50) NULL,
	[sTel] VARCHAR(20) NULL,
	[dQualifiedPDI] datetime NULL,
	[FKiQSInstanceID] INT NULL,
	[iTitle] INT NULL,
	[enumOccupatation] INT NULL default((0)),
	[sOtherVehiclesOwned] VARCHAR(256) NULL,
	[iMedicalConditions] INT NULL,
	[iEmploymentType] INT NULL,
	[iBusinessCategory] INT NULL,
	[iSecondaryOccupation] INT NULL,
	[iSecondaryEmploymentType] INT NULL,
	[iSecondaryBusinessCategory] INT NULL,
	[sEmploymentType] VARCHAR(256) NULL,
	[sBusinessCategory] VARCHAR(256) NULL,
	[sSecondaryOccupation] VARCHAR(256) NULL,
	[sSecondaryEmploymentType] VARCHAR(256) NULL,
	[sSecondaryBusinessCategory] VARCHAR(256) NULL,
	[sMaritalStatus] VARCHAR(256) NULL,
	[iUKResidentMonth] INT NULL,
	[iUKResidentYear] INT NULL,
	[bSinceBirth] bit NULL,
	[FKiPolicyVersionID] INT NULL,
	[iDriverNo] INT NULL,
	[dDrivingtest] datetime NULL,
	[sClaimFreeCaravanning] VARCHAR(256) NULL,
	[iTowing] INT NULL,
	[sAddressLine1] VARCHAR(256) NULL,
	[sAddressLine2] VARCHAR(256) NULL,
	[sAddressLine3] VARCHAR(256) NULL,
	[iFinancialinterest] INT NULL,
	[sTown] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiQSInstanceIDXIGUID] uniqueidentifier NULL,
	[OFTAreThereAnySpecifiedDrivers] int NOT NULL default(0),
	[OFTWhatdrivingpermissionsarerequired] int NOT NULL default(0),
)