IF OBJECT_ID('ERP_Task', 'U') IS NOT NULL DROP TABLE dbo.ERP_Task

	
CREATE TABLE [ERP_Task]
(
	[ID] INT NULL,
	[FKiTaskTypeID] INT NULL,
	[FKiAssociatedID] INT NULL,
	[sAssociatedWith] INT NULL,
	[sTaskDesc] NVARCHAR(50) NULL,
	[bSignedOff] bit NULL,
	[sComments] NVARCHAR(255) NULL,
	[FKiProcessStepID] INT NULL,
	[FKiRoleID] INT NULL,
	[iTemplateType] INT NULL,
	[dStart] datetime NULL,
	[dDue] datetime NULL,
	[iStatus] INT NULL,
	[sTaskInstructions] NVARCHAR(100) NULL,
	[sCompletionNotes] NVARCHAR(255) NULL,
	[iRelatedID] INT NULL,
	[iDaysFromZeroDay] INT NULL,
	[iDuration] INT NULL,
	[iDeleted] INT NULL,
	[FKiTeamID] INT NULL,
	[FKsUserID] NVARCHAR(30) NULL,
	[FKiOrderID] INT NULL,
	[sName] NVARCHAR(50) NULL,
	[sNotes] NVARCHAR(250) NULL,
	[sAlert] NVARCHAR(50) NULL,
	[sLogo] NVARCHAR(50) NULL,
	[refUserReason] INT NULL,
	[dEnd] datetime NULL,
	[iDays] float NULL,
	[sDetails] NVARCHAR(50) NULL,
	[dApproved] datetime NULL,
	[FKsApproveByID] NVARCHAR(50) NULL,
	[iType] INT NULL,
	[sRejectedReason] NVARCHAR(250) NULL,
	[iDaysSick] float NULL,
	[iDaysOther] float NULL,
	[iDaysHols] float NULL,
	[FKiEmployeeID] INT NULL,
	[FKiApproveID] INT NULL,
	[sSecureAuthentication] NVARCHAR(50) NULL,
	[FKszxUserID] NVARCHAR(30) NULL,
	[zDaysAllocated] float NULL,
	[iApprovalStatus] INT NULL,
	[iEstHours] INT NULL,
	[iEstMinutes] INT NULL,
	[iWarningStatus] INT NULL,
	[iNotificationType] INT NULL,
	[iEmailMe] INT NULL,
	[sEndTime] NVARCHAR(50) NULL,
	[dExactTimeDue] smalldatetime NULL,
	[dReminder] smalldatetime NULL,
	[tReminder] NVARCHAR(50) NULL,
	[sManagerMessage] NVARCHAR(120) NULL,
	[iPriority] INT NULL,
	[iReminderStatus] INT NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[zXUpdtdId] INT NULL,
	[dLastRecurDate] datetime NULL,
	[tLastRecur] VARCHAR(20) NULL,
	[iNotificationRecur] INT NULL,
	[iSubType] INT NULL,
	[refDiaryCategoryID] INT NULL,
	[refDepartmentID] INT NULL,
	[FKiBatchTemplateID] INT NULL,
	[FKiTaskSetID] INT NULL,
	[FKiACPolicyID] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[FKiOrgID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiProductID] INT NULL,
	[FKsCompletedByID] VARCHAR(30) NULL,
	[sFunction] VARCHAR(4000) NULL,
	[FKsPolicyNo] VARCHAR(120) NULL,
	[FKiCustomerID] INT NULL default((0)),
	[iTransactionType] INT NULL,
	[FKsClientReferenceNumber] VARCHAR(120) NULL,
	[FKiPolicyVersionID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[iDiaryType] INT NULL default((10)),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiClaimID] INT NULL,
	[FKiCompliantsID] INT NULL,
	[FKiUserID] INT NULL,
	[FKiRequiredDocID] INT NULL,
	[FKiQSInstanceIDXIGUID] UNIQUEIDENTIFIER NULL
)