IF OBJECT_ID('MakeAChange_T', 'U') IS NOT NULL DROP TABLE dbo.MakeAChange_T

	
CREATE TABLE [MakeAChange_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FKiCategoryID] INT NULL,
	[sFirstNameMC] VARCHAR(60) NULL,
	[sLastNameMC] VARCHAR(60) NULL,
	[sAddressLine1] VARCHAR(60) NULL,
	[sAddressLine2] VARCHAR(60) NULL,
	[sAddressLine3] VARCHAR(60) NULL,
	[sTown] VARCHAR(60) NULL,
	[sRegistrationNumber] VARCHAR(120) NULL,
	[sDriverFirstName] VARCHAR(60) NULL,
	[sDriverLastName] VARCHAR(60) NULL,
	[sMob] VARCHAR(15) NULL,
	[sDriverDOB] datetime NULL,
	[sRegistrationNo] VARCHAR(15) NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[iStatus] INT NULL,
	[sPostCode] NVARCHAR(10) NULL,
	[sParkingPostCode] NVARCHAR(10) NULL,
	[sWheredoyoustoreUpdated] NVARCHAR(50) NULL,
	[iWhatisthelocationofyourmotorhomeovernight] INT NULL,
	[iTitleMC] INT NULL,
	[sTypeOfCaravanUpdated] INT NULL,
	[sCaravanMake] INT NULL,
	[sModelofCaravan] VARCHAR(120) NULL,
	[sEngineSize] VARCHAR(60) NULL,
	[iCurrentMileage] INT NULL,
	[bISLeftHandDrive] INT NULL,
	[iYearOfManufactureUpdated] INT NULL,
	[iYearOfOwnership] INT NULL,
	[dDateofpurchase] datetime NULL,
	[sVehicleModificationsMC] INT NULL,
	[sVehicleModificationsDescription] VARCHAR(520) NULL,
	[iNoofSeats] INT NULL,
	[iVehicleSecurity] INT NULL,
	[iTypeofdevice] INT NULL,
	[sVehicleOwner] VARCHAR(15) NULL,
	[sVehicleKeeper] VARCHAR(15) NULL,
	[iCurrentCaravanValue] decimal(18,6) NULL,
	[iSex] INT NULL,
	[dDOB] datetime NULL,
	[iMaritalStatusMC] INT NULL,
	[sDrivingQualification] VARCHAR(50) NULL,
	[dDateTestPassed] datetime NULL,
	[sUKResidency] datetime NULL,
	[ienumRelationship] INT NULL,
	[ienumOccupatation] INT NULL,
	[sEmploymentType] INT NULL,
	[sBusinessCategory] INT NULL,
	[sSecondaryOccupation] INT NULL,
	[sSecondaryEmploymentType] INT NULL,
	[sSecondaryBusinessCategory] INT NULL,
	[sEmail] VARCHAR(50) NULL,
	[dCoverStartMC] datetime NULL,
	[FKiQSInstanceID] INT NULL,
	[FKiDriverID] INT NULL,
	[iAnyClaimsMC] INT NULL,
	[iAnyConvictionsMC] INT NULL,
	[iMedicalConditionsMC] INT NULL,
	[sClaimssName] INT NULL,
	[iWhoseFaultMC] INT NULL,
	[dClaimsDateMC] datetime NULL,
	[rCostInjuredMC] float NULL,
	[rTotalClaimCostMC] float NULL,
	[dConvictionDateMC] datetime NULL,
	[irefConvictionMC] INT NULL,
	[rFineMC] float NULL,
	[iPenaltyPointsMC] INT NULL,
	[sLengthOfSuspensionMC] INT NULL,
	[refMedicalConditionMC] INT NULL,
	[dDiagnosedMC] datetime NULL,
	[iUKResidentMonth] INT NULL,
	[iUKResidentYear] INT NULL,
	[bSinceBirth] bit NULL,
	[AdditionalWindows] bit NULL default((0)),
	[SideSkirts] bit NULL default((0)),
	[Bumpers] bit NULL default((0)),
	[StandardEnginesReplacement] bit NULL default((0)),
	[CamperVanConversion] bit NULL default((0)),
	[SunRoof] bit NULL default((0)),
	[Exhaust] bit NULL default((0)),
	[SuspensionUpgraded] bit NULL default((0)),
	[FrontRearSpoiler] bit NULL default((0)),
	[TintedWindows] bit NULL default((0)),
	[LPGConversion] bit NULL default((0)),
	[TowBar] bit NULL default((0)),
	[PaintworkStandard] bit NULL default((0)),
	[UpgradedBrakes] bit NULL default((0)),
	[PopUpRoof] bit NULL default((0)),
	[Upholsterychanges] bit NULL default((0)),
	[MCOther] bit NULL default((0)),
	[OtherVehiclemodifications] VARCHAR(250) NULL,
	[sHomenumberMC] VARCHAR(15) NULL,
	[iSecondaryOccupationMC] INT NULL,
	[dEffectiveFromMC] datetime NULL,
	[dCancellationDateMC] datetime NULL,
	[sCancellationReasonMC] VARCHAR(MAX) NULL,
	[izXDeleted] INT NULL,
	[iAccidentTypeMC] INT NULL,
	[sOtherChangeMC] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)