IF OBJECT_ID('MedicalCondition_T', 'U') IS NOT NULL DROP TABLE dbo.MedicalCondition_T

	
CREATE TABLE [MedicalCondition_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(100) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[dDiagnosed] datetime NULL,
	[sCondition] VARCHAR(250) NULL,
	[FKiDriverID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACPolicyID] INT NULL,
	[bDVLAInformed] bit NULL,
	[bREgisteredDisabled] bit NULL,
	[bDisabledBadgeHolder] bit NULL,
	[FKiClientID] INT NULL,
	[iClientConditionID] INT NULL,
	[iOriginal] INT NULL,
	[refMedicalCondition] INT NULL,
	[bLicRestrictions] bit NULL,
	[sMedication] VARCHAR(250) NULL,
	[iConditionDeteriorating] INT NULL,
	[FKiPolicyVersionID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiDriverIDXIGUID] uniqueidentifier NULL
)