IF OBJECT_ID('MTClaims_T', 'U') IS NOT NULL DROP TABLE dbo.MTClaims_T

	
CREATE TABLE [MTClaims_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[XICreatedBy] VARCHAR(15) NOT NULL,
	[XICreatedWhen] datetime NOT NULL,
	[XIUpdatedBy] VARCHAR(15) NOT NULL,
	[XIUpdatedWhen] datetime NOT NULL,
	[XIDeleted] INT NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER NOT NULL default(newid()),
	[sName] VARCHAR(256) NULL,
	[sDescription] VARCHAR(256) NULL,
	[sCode] VARCHAR(256) NULL,
	[iStatus] INT NULL,
	[iType] INT NULL,
	[iClaimType] INT NULL,
	[dDate] date NULL,
	[bPersonalInjury] [bit] NULL,
	[rCostOwn] [float] NULL,
	[rCostParty] [float] NULL,
	[iNCDLost] INT NULL,
	[iWhoseFault] INT NULL,
	[iWho] INT NULL,
	[FkiDriverID] INT NULL,
	[sNotes] VARCHAR(max) NULL,
	[sLostInjured] VARCHAR(256) NULL,
	[iClaimStatus] INT NULL,
	[iClaimSettled] INT NULL,
	[FkiQSinstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[dFTStartDate] date NULL,
	[dFTEndDate] date NULL,
	[sFTRatingMethod] VARCHAR(50) NULL,
	[sFTPriorInsurer] VARCHAR(50) NULL,
	[iFTVehicleYears] INT NULL,
	[iFTTotalNumberOfClaimsIncurredDuringThisPeriod] INT NULL,
	[iFTTotalNumberOfWindscreenClaims] INT NULL,
	[iFTAccidentalDamage] INT NULL,
	[iFTCoverBasisINThisPeriod] INT NULL,
	[iFTFireandTheftExcess] INT NULL,
	[iFTWindScreenExcess] INT NULL,
	[iFTTotalNumberOfClaimsincludingOutstanding] INT NULL,
	[iFTClaimsPaidAccidentalDamage] INT NULL,
	[iFTClaimsOutstandingAccidentalDamage] INT NULL,
	[iFTClaimsPaidThirdParty] INT NULL,
	[iFTClaimsPaidFireandTheft] INT NULL,
	[sFTTypeOfClaims] INT NULL,
	[dFTWhenwastheclaim] date NULL,
	[sFTWhatwastheclaim] VARCHAR(250) NULL,
	[iFTAmountofclaim] INT NULL,
	[sFTWasthedriveratfault] VARCHAR(250) NULL,
	[sFTNameddriverinvolved] VARCHAR(250) NULL,
	[iFTRatingMethod] INT NULL,
	[iFTTotalclaimvalueinperiod] float NULL,
	[iFTClaimsOutstandingFireandTheft] INT NULL,
	[iFTClaimsOutstandingThirdParty] INT NULL,
	[IAnyfleetrelatedlosses] INT NULL,
	[iFTNumberOfwindscreenClaimspaidandOutstanding] INT NULL,
	[iFTNumberofclaimsoutstanding] INT NULL,
	[sFTNCDratedvehicleatstartofperiod] VARCHAR(256) NULL,
	[iFTAnymotorrelatedlossesinNCDperiod] INT NULL,
	[iDriveratfault] int NULL,
	[iNCBlostorProtectedlifelost] int NULL
)