IF OBJECT_ID('MTDriver_T', 'U') IS NOT NULL DROP TABLE dbo.MTDriver_T

	
CREATE TABLE [MTDriver_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[XICreatedBy] VARCHAR(15) Not NULL,
	[XICreatedWhen] datetime NOT NULL,
	[XIUpdatedBy] VARCHAR(15) Not NULL,
	[XIUpdatedWhen] datetime NOT NULL,
	[XIDeleted] INT NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sName] VARCHAR(256) NULL,
	[sDescription] VARCHAR(256) NULL,
	[sCode] VARCHAR(256) NULL,
	[iStatus] INT NULL,
	[iType] INT NULL,
	[FkiQSinstanceID] INT NULL,
	[iTitle] INT NULL,
	[dDateOfBirth] date NULL,
	[iSeX] INT NULL,
	[iMaritalstautus] INT NULL,
	[iLicenseType] INT NULL,
	[dDateTestPassed] date NULL,
	[bBikeLiesencemorethanone1year] bit NULL,
	[iFullorPart] INT NULL,
	[bAdditionalBusinessuse] bit NULL,
	[iOccupation] INT NULL,
	[iRelationship] INT NULL,
	[iMainEmployeeType] INT NULL,
	[iTradeOccupation] INT NULL,
	[iUseage] INT NULL,
	[iTelephoneNo] bigint NULL,
	[iCommuting] bigint NULL,
	[sFirstName] VARCHAR(256) NULL,
	[SLastName] VARCHAR(256) NULL,
	[sPartTime] VARCHAR(256) NULL,
	[sBusinessPartTime] VARCHAR(256) NULL,
	[sPartTimeEmployeementType] VARCHAR(256) NULL,
	[sAddress] VARCHAR(MAX) NULL,
	[sPostcode] VARCHAR(50) NULL,
	[sEmail] VARCHAR(256) NULL,
	[sMainEmployeeStatus] VARCHAR(256) NULL,
	[iNatureofBusiness] INT NULL,
	[FkiQSinstanceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[dUkResidency] INT NULL,
	[bMainDriver] bit NOT NULL default((0)),
	[iAge] INT NULL,
	[IDrivingLicenceLength] INT NULL,
	[MTAddressline1] VARCHAR(512) NULL,
	[MTAddressline2] VARCHAR(512) NULL,
	[MTAddressline3] VARCHAR(512) NULL,
	[iMainEmployeeStatus] INT NULL,
	[iMTEmploymentStatus] INT NULL,
	[OFTAreThereAnySpecifiedDrivers] int NOT NULL default(0),
	[OFTWhatdrivingpermissionsarerequired] int NOT NULL default(0),
	[dFTYearlicenceobtained] date NULL,
	[iFTTypeOfDrivingLicence] int NULL,
	[iFTAreThereAnySpecifiedDrivers] int NULL,
	[sFTPostcode] varchar(50) NULL ,
	[dWhendidyoupassyourdrivingtest] date NULL,
	[iYrsFullUKLic] int NULL,
	[iMTUse] int NULL,
	[iSDPUse] int NULL,
	[iMTUseage] int NULL
)