IF OBJECT_ID('PFScheme_T', 'U') IS NOT NULL DROP TABLE dbo.PFScheme_T

	
CREATE TABLE [PFScheme_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiEnterpriseID] INT NULL,
	[FKiSupplierID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiACAccountID] INT NULL,
	[sSchemeRefCode] VARCHAR(50) NULL,
	[iNoPaymentDays] INT NULL,
	[iProRata] INT NULL,
	[iNoInstallments] INT NULL,
	[zGrossRatePC] float NULL,
	[iCustomerType] INT NULL,
	[iPolicyType] INT NULL,
	[iDirectDebitDay] INT NULL,
	[FKiEDITypeID] INT NULL,
	[iEDITransmissionMethod] INT NULL,
	[sEDIPrimaryAddress] VARCHAR(250) NULL,
	[sEDISecondaryAddress] VARCHAR(250) NULL,
	[sEDITestAddress] VARCHAR(250) NULL,
	[iEDIMode] INT NULL,
	[sEDIPassword] VARCHAR(100) NULL,
	[sEDIUserName] VARCHAR(50) NULL,
	[iCollectDay] INT NULL,
	[iRecourse] INT NULL,
	[MinDepositRate] float NULL,
	[Apr] decimal(18,6) NULL,
	[sShopCode] VARCHAR(64) NULL,
	[sClassofBusiness] VARCHAR(64) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)