IF OBJECT_ID('ProductVersions_T', 'U') IS NOT NULL DROP TABLE dbo.ProductVersions_T

	
CREATE TABLE [ProductVersions_T]
(
	[ID] INT NOT NULL PRIMARY KEY Identity(1,1),
	[sName] VARCHAR(30) NULL,
	[sDescription] VARCHAR(MAX) NULL,
	[FKiScriptID] INT NULL,
	[FKiProductID] INT NULL,
	[iStatus] INT NULL,
	[dActiveFrom] datetime NULL,
	[dActiveTo] datetime NULL,
	[CreatedTime] datetime NULL,
	[CreatedBy] INT NULL,
	[CreatedBySYSID] VARCHAR(512) NULL,
	[UpdatedBy] INT NULL,
	[UpdatedBySYSID] VARCHAR(512) NULL,
	[UpdatedTime] datetime NULL,
	[FKiMTAScriptID] INT NULL,
	[FKiCancelScriptID] INT NULL,
	[sPostCodeLookupType] NVARCHAR(50) NULL,
	[FKiUserID] INT NOT NULL default((0)),
	[zXCrtdBy] VARCHAR(120) NULL,
	[zXCrtdWhn] datetime NOT NULL default(getdate()),
	[zXUpdtdBy] VARCHAR(120) NULL,
	[zXUpdtdWhn] datetime NOT NULL default(getdate()),
	[izXDeleted] INT NULL default((0)),
	[FkiClassID] INT NULL,
	[rDefaultPrice] float NULL,
	[bIsIndicativePrice] bit NULL,
	[rAdditionalLoad] float NULL,
	[sClaculation] VARCHAR(16) NULL,
	[FKiPartialScriptID] INT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiQSDefinitionID] INT NULL,
	[FKiQSDefinitionIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiPreScriptID] INT NULL,
	[FKiPostScriptID] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiTemplateIDXIGUID] uniqueidentifier NULL,
	[sExcelCalcPath] nvarchar(2048) NULL,
	[iCalculation] int NULL,
	[FKiScriptIDXIGUID] uniqueidentifier NULL,
	[FKiMTAScriptIDXIGUID] uniqueidentifier NULL,
	[FKiPostScriptIDXIGUID] uniqueidentifier NULL,
	[FKiPreScriptIDXIGUID] uniqueidentifier NULL,
	[FKiPartialScriptIDXIGUID] uniqueidentifier NULL,
	[FKiCancelScriptIDXIGUID] uniqueidentifier NULL,

)