IF OBJECT_ID('Product', 'U') IS NOT NULL DROP TABLE dbo.Product

	
CREATE TABLE [Product]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(100) NULL,
	[sDescription] VARCHAR(100) NULL,
	[sImage] VARCHAR(100) NULL,
	[sType] VARCHAR(100) NULL,
	[dDate] datetime NULL,
	[sVersion] VARCHAR(100) NULL,
	[sProductCode] VARCHAR(100) NULL,
	[dActiveFrom] datetime NULL,
	[dActiveTo] datetime NULL,
	[iSeqMethod] bigint NULL,
	[sSeqPrefix] VARCHAR(20) NULL,
	[sSeqFunction] VARCHAR(250) NULL,
	[iStartSequence] bigint NULL,
	[iSequence] bigint NULL,
	[iEndSeqence] bigint NULL,
	[iNextSeqStart] bigint NULL,
	[iNextSeqEnd] bigint NULL,
	[rMinPremium] float NULL,
	[rMinIPT] float NULL,
	[zDefaultAdmin] float NULL,
	[zDefaultDeposit] float NULL,
	[FKiSupplierID] INT NULL,
	[iStatus] INT NULL default((0)),
	[izXDeleted] INT NULL default((0)),
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[sNotes] VARCHAR(250) NULL,
	[iType] INT NULL,
	[zCommission] float NULL,
	[iCommissionType] INT NULL,
	[iAdminType] INT NULL,
	[iDepositType] INT NULL,
	[iTaxType] INT NULL,
	[FKiEnterpriseID] INT NULL,
	[FKiEDITypeID] INT NULL,
	[refAnalysis1] INT NULL,
	[sStartSequence] VARCHAR(120) NULL,
	[sSequence] VARCHAR(120) NULL,
	[sEndSeqence] VARCHAR(120) NULL,
	[sNextSeqStart] VARCHAR(120) NULL,
	[sNextSeqEnd] VARCHAR(120) NULL,
	[rCancellationFee] float NULL,
	[rDefaultAmount] float NULL,
	[iDefaultAmountType] INT NULL,
	[sAssumptions] VARCHAR(MAX) NULL,
	[sMoreDetails] VARCHAR(MAX) NULL,
	[bIsCoverAbroad] bit NULL default((0)),
	[iDriverEDICount] INT NULL,
	[iClaimEDICount] INT NULL,
	[iCovictionEDICount] INT NULL,
	[iEndorsementEDICount] INT NULL,
	[rInsurerCharge] float NULL,
	[iMinPaymentCalType] INT NULL,
	[rPaymentCharge] float NULL,
	[iDriverEDICommaCount] INT NULL,
	[iClaimEDICommaCount] INT NULL,
	[iConvictionEDICommaCount] INT NULL,
	[iEndorsementEDICommaCount] INT NULL,
	[tEndTime] VARCHAR(50) NULL,
	[FkiClassID] INT NULL,
	[rMTACharge] float NULL,
	[bIsSequence] bit NULL default((1)),
	[bIsEmail] bit NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[iAddDaysToEndDate] INT NOT NULL default((0)),
	[bIsInternalOnly] bit NOT NULL default((0)),
	[sCode] VARCHAR(256) NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[FKiOrgID] INT NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[iButtonType] INT NULL,
	[bAutoLapse] bit NULL,
	[FKiTemplateID] bigint NULL,
	[iXmlType] INT NULL,
	[FKiTemplateIDXIGUID] UNIQUEIDENTIFIER NULL,
	[sRemindernotes] VARCHAR (MAX),
	[sEmail] VARCHAR (256) NULL
)