IF OBJECT_ID('ProductAddon_T', 'U') IS NOT NULL DROP TABLE dbo.ProductAddon_T

	
CREATE TABLE [ProductAddon_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(255) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[refAddon] INT NULL,
	[rPriceAddOn] float NULL,
	[bNew] bit NULL,
	[bMTA] bit NULL,
	[bRenew] bit NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiProductID] INT NULL,
	[zCommission] float NULL,
	[iCommissionType] INT NULL,
	[zDefaultAdmin] float NULL,
	[iAdminType] INT NULL,
	[zDefaultDeposit] float NULL,
	[iDepositType] INT NULL,
	[iTaxType] INT NULL,
	[FKiSupplierID] INT NULL,
	[iPeriodOfCover] INT NULL,
	[refAnalysis1] INT NULL,
	[iVersion] INT NULL,
	[sIPID] VARCHAR(MAX) NULL,
	[sBooklet] VARCHAR(MAX) NULL,
	[sMoreDetails] VARCHAR(MAX) NULL,
	[sAddonContent] VARCHAR(MAX) NULL,
	[rInsurerCharge] float NULL,
	[rIPT] float NULL,
	[rCoverLevel] float NULL,
	[sDisplayName] VARCHAR(255) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[bIsInternalOnly] bit NOT NULL default((0)),
	[dActiveFrom] datetime NULL,
	[dActiveTo] datetime NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[bIsIPT] bit NULL,
	[rSalePriceExcludeIPT] float NULL,
	[rCostPrice] float NULL,
	[rMargin] float NULL,
	[bIsAutoRenew] bit NULL,
	[FKiClassID] INT NULL,
	[iPurchaseCount] int NULL,
	[sAddonName] varchar(256) NULL,
	[iQuantity] int NOT NULL DEFAULT((0)),
	[rAdmin] float NULL
)