IF OBJECT_ID('refAddon_T', 'U') IS NOT NULL DROP TABLE dbo.refAddon_T

	
CREATE TABLE [refAddon_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(255) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[rPrice] float NULL,
	[FKiSupplierID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiEnterpriseID] INT NULL,
	[refProductTypeID] INT NULL,
	[iBusinessType] INT NULL,
	[sAddonContent] VARCHAR(MAX) NULL,
	[sStartSequence] VARCHAR(120) NULL,
	[sSequence] VARCHAR(120) NULL,
	[sEndSeqence] VARCHAR(120) NULL,
	[sSeqPrefix] VARCHAR(20) NULL,
	[sNextSeqStart] VARCHAR(120) NULL,
	[sNextSeqEnd] VARCHAR(120) NULL,
	[XIGUID] UNIQUEIDENTIFIER NOT NULL default(newid()),
	[XIDeleted] INT NOT NULL,
	[XICreatedBy] VARCHAR(64) Not NULL,
	[XIUpdatedBy] VARCHAR(64) Not NULL,
	[XICreatedWhen] datetime NOT NULL,
	[XIUpdatedWhen] datetime NOT NULL,
)