IF OBJECT_ID('refConfiguration_T', 'U') IS NOT NULL DROP TABLE dbo.refConfiguration_T

	
CREATE TABLE [refConfiguration_T]
(
	[id] INT NOT NULL,
	[sName] NVARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] NVARCHAR(250) NULL,
	[zVATPC] float NULL,
	[rHourlyRate] float NULL,
	[rDailyCostBase] float NULL,
	[iSingleTuroverUnit] INT NULL,
	[sDepartment] NVARCHAR(50) NULL,
	[sExportFolder] NVARCHAR(250) NULL,
	[iRecentDays] INT NULL,
	[iMediumDays] INT NULL,
	[iLongDays] INT NULL,
	[iWarningMinutes] INT NULL,
	[iCriticalMinutes] INT NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[iDaysToTeleBox1] INT NULL,
	[iDaysToTeleBox2] INT NULL,
	[iDaysToTeleBox3] INT NULL,
	[zIPT] float NULL,
	[zPFDepositMinimum] float NULL,
	[zMonday] float NULL,
	[zTuesday] float NULL,
	[zWednesday] float NULL,
	[zThursday] float NULL,
	[zFriday] float NULL,
	[zSaturday] float NULL,
	[zSunday] float NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)