IF OBJECT_ID('refGoalType_T', 'U') IS NOT NULL DROP TABLE dbo.refGoalType_T

	
CREATE TABLE [refGoalType_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[sLogo] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[sIcon] VARCHAR(50) NULL,
	[iVisualisationType] INT NULL,
	[sTranslationExpression] VARCHAR(250) NULL,
	[iProgressUpdates] INT NULL,
	[iProgressSpacing] INT NULL,
	[iProgressSpacingType] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[iCalculationMethod] INT NULL,
	[iCalculationLast] INT NULL,
	[iCalculationIncludes] INT NULL,
	[sFormatExpression] VARCHAR(250) NULL,
	[iTargetComparison] INT NULL,
	[iProgressTrendComparison] INT NULL,
	[iProgressVisualisation] INT NULL,
	[iProgressCount] INT NULL,
	[iGeneralFormat] INT NULL,
	[iProgressCreationMethod] INT NULL,
	[iWhichDays] INT NULL,
	[FKsUserID] VARCHAR(30) NULL,
	[sChainUpOverrideExpression] VARCHAR(250) NULL,
	[iSequenceStart] INT NULL,
	[iUpdateType] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)