IF OBJECT_ID('refType_T', 'U') IS NOT NULL DROP TABLE dbo.refType_T

	
CREATE TABLE [refType_T]
(
	[id] INT NOT NULL,
	[sName] NVARCHAR(50) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] NVARCHAR(250) NULL,
	[zXCrtdBy] NVARCHAR(15) NULL,
	[zXCrtdWhn] smalldatetime NULL,
	[zXUpdtdBy] NVARCHAR(15) NULL,
	[zXUpdtdWhn] smalldatetime NULL,
	[sMailAddress] NVARCHAR(100) NULL,
	[sGroupMain] NVARCHAR(50) NULL,
	[sAddBO] NVARCHAR(50) NULL,
	[sAddGroup] NVARCHAR(50) NULL,
	[sAddCol1] NVARCHAR(50) NULL,
	[sAddCol2] NVARCHAR(50) NULL,
	[sAddSearchGroup] NVARCHAR(50) NULL,
	[sAddListGroup] NVARCHAR(50) NULL,
	[sQuestionSet] text NULL,
	[sCode] VARCHAR(20) NULL,
	[sAddPolicyBO] VARCHAR(100) NULL,
	[FKiCumulativeCalculationID] INT NULL,
	[iPolicyEnabled] INT NULL,
	[enumInsuranceTypeID] INT NULL,
	[sPreHTML] VARCHAR(250) NULL,
	[sPostHTML] VARCHAR(250) NULL,
	[iPolicyPopup] INT NULL,
	[iRenewalVehicles] INT NULL,
	[iEndorsements] INT NULL,
	[sInviteGroup] VARCHAR(100) NULL,
	[FKiRenewalCallTypeID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)