IF OBJECT_ID('Requirement_T_Audit', 'U') IS NOT NULL DROP TABLE dbo.Requirement_T_Audit

	
CREATE TABLE [Requirement_T_Audit]
(
	[iStatus] INT NULL,
	[iType] INT NULL,
	[iTransactionType] INT NULL,
	[iValidationStatus] INT NULL,
	[iDaysFromCalc] INT NULL,
	[iRequestStage] INT NULL,
	[iAppliesTo] INT NULL,
	[iImplementation] INT NULL,
	[iMultiple] INT NULL,
	[iSentStatus] INT NULL,
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(256) NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(256) NULL,
	[sAlert] VARCHAR(256) NULL,
	[FKiOrgID] INT NULL,
	[FKiClientID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiPolicyID] INT NULL,
	[FKiACTransactionID] INT NULL,
	[FKiProductID] INT NULL,
	[dDue] datetime NULL,
	[dRequested] datetime NULL,
	[dReceived] datetime NULL,
	[FKizXDoc] VARCHAR(256) NULL,
	[iDueInDays] INT NULL,
	[refType] float NULL,
	[sCode] VARCHAR(256) NULL,
	[FKiTransactionTypeID] INT NULL,
	[FKitechDocID] INT NULL,
	[dFollowUp] datetime NULL,
	[sPostCode] VARCHAR(256) NULL,
	[sInvalidIssues] VARCHAR(256) NULL,
	[iVersion] INT NULL,
	[sFunction] VARCHAR(256) NULL,
	[refChaseStatus] float NULL,
	[iDocumentCount] INT NULL,
	[dtLastProgress] datetime NULL,
	[iMultipleInstance] INT NULL,
	[bAdd] bit NULL,
	[dInception] datetime NULL,
	[dtSent] datetime NULL,
	[FKsUserSentID] VARCHAR(256) NULL,
	[FKiUserID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[dtProgressChaseStatus] datetime NULL,
	[sUpdatedBy] VARCHAR(256) NULL,
	[sUpdatedWhen] VARCHAR(256) NULL,
	[dDatetobeCancelled] datetime NULL,
	[FKsPolicyNo] VARCHAR(256) NULL,
	[FKiInstanceID] INT NULL,
	[zXAuditCrtdBy] VARCHAR(15) NULL,
	[zXAuditCrtdWhn] datetime NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)