IF OBJECT_ID('Requirement_T', 'U') IS NOT NULL DROP TABLE dbo.Requirement_T

	
CREATE TABLE [Requirement_T]
(
	[ID] INT NOT NULL,
	[sName] VARCHAR(250) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiClientID] INT NULL,
	[FKiSupplierID] INT NULL,
	[FKiACTransactionID] INT NULL,
	[zXCrtdBy] VARCHAR(64) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(64) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiProductID] INT NULL,
	[dDue] datetime NULL,
	[dReceived] datetime NULL,
	[dRequested] datetime NULL,
	[FKizXDoc] VARCHAR(250) NULL,
	[FKiPolicyID] INT NULL,
	[iDueInDays] INT NULL,
	[refType] INT NULL,
	[sCode] VARCHAR(30) NULL,
	[FKiTransactionTypeID] INT NULL,
	[iTransactionType] INT NULL,
	[FKitechDocID] INT NULL,
	[dFollowUp] datetime NULL,
	[sPostCode] VARCHAR(50) NULL,
	[iValidationStatus] INT NULL,
	[sInvalidIssues] VARCHAR(250) NULL,
	[iVersion] INT NULL,
	[sFunction] VARCHAR(4000) NULL,
	[iDaysFromCalc] INT NULL,
	[iRequestStage] INT NULL,
	[iAppliesTo] INT NULL,
	[iDocumentCount] INT NULL,
	[refChaseStatus] INT NULL,
	[dtLastProgress] datetime NULL,
	[iImplementation] INT NULL,
	[iMultiple] INT NULL,
	[iMultipleInstance] INT NULL,
	[bAdd] bit NULL,
	[dInception] datetime NULL,
	[iSentStatus] INT NULL,
	[dtSent] datetime NULL,
	[FKsUserSentID] VARCHAR(30) NULL,
	[FKiUserID] INT NULL,
	[FKsPolicyNo] VARCHAR(120) NULL,
	[dtProgressChaseStatus] datetime NULL,
	[sUpdatedBy] VARCHAR(256) NULL,
	[sUpdatedWhen] datetime NULL,
	[dDatetobeCancelled] datetime NULL,
	[FKsClientReferenceNumber] VARCHAR(120) NULL,
	[sPolicyHolderName] VARCHAR(250) NULL,
	[dRequiredDate] datetime NULL,
	[FKiPolicyVersionID] INT NULL,
	[FKsUserID] VARCHAR(64) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sDescription] VARCHAR(256) NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[bIsSelection] bit NOT NULL DEFAULT((0)),
	[FKiRequiredDocID] INT NULL,
	[bIsPolicyDocument] bit NOT NULL DEFAULT((0)),
	[FKiQSInstanceIDXIGUID] UNIQUEIDENTIFIER NULL
)