IF OBJECT_ID('Supplier_T', 'U') IS NOT NULL DROP TABLE dbo.Supplier_T

	
CREATE TABLE [Supplier_T]
(
	[id] INT NOT NULL,
	[sName] VARCHAR(128) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL,
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[FKiPaymentTermsID] INT NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKzxDocLogoID] INT NULL,
	[FKiACAccountID] INT NULL,
	[sSupplierBrokerRef] VARCHAR(50) NULL,
	[sEMail] VARCHAR(250) NULL,
	[sInsurerCode] VARCHAR(20) NULL,
	[sCustomerTel] VARCHAR(50) NULL,
	[sClaimsTel] VARCHAR(50) NULL,
	[sClaimsTelAbroad] VARCHAR(50) NULL,
	[sFullAddress] VARCHAR(250) NULL,
	[sAdminAddress] VARCHAR(250) NULL,
	[sFSANo] VARCHAR(100) NULL,
	[sPostCode] VARCHAR(10) NULL,
	[dTOBA] datetime NULL,
	[sCancelPeriod] VARCHAR(50) NULL,
	[bRiskTransfer] bit NULL,
	[bCoMingling] bit NULL,
	[bCommissionTransfer] INT NULL,
	[enumInsurerCodeID] INT NULL,
	[FKiSysApplicationID] INT NULL,
	[sContactNo] VARCHAR(30) NULL,
	[sContactName] VARCHAR(50) NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[rBalance] float NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FkiMasterInsurerID] bigint NULL,
	[FKiACAccountIDXIGUID] UNIQUEIDENTIFIER NULL
)