IF OBJECT_ID('Term_T', 'U') IS NOT NULL DROP TABLE dbo.Term_T

	
CREATE TABLE [Term_T]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sName] VARCHAR(120) NULL,
	[iStatus] INT NULL,
	[izXDeleted] INT NULL default((0)),
	[sNotes] VARCHAR(250) NULL,
	[sAlert] VARCHAR(50) NULL,
	[iType] INT NULL,
	[FKiOrgID] INT NULL,
	[iOptional] INT NULL,
	[sTerms] text NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[FKiProductID] INT NULL,
	[FKiACPolicyID] INT NULL,
	[iAppliesTo] INT NULL,
	[sCode] VARCHAR(20) NULL,
	[iProductTermID] INT NULL,
	[bApply] bit NULL,
	[iVersion] INT NULL,
	[sFunction] VARCHAR(4000) NULL,
	[iNo] VARCHAR(30) NULL,
	[sValue] VARCHAR(50) NULL,
	[FKiQSInstanceID] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[bISGenerateonQuote] bit NULL,
	[sTemplate] VARCHAR(128) NULL,
	[sApplicableTo] VARCHAR(128) NULL,
	[FKiQuoteID] bigint NULL
)