IF OBJECT_ID('TraceTransactions_T', 'U') IS NOT NULL DROP TABLE dbo.TraceTransactions_T

	
CREATE TABLE [TraceTransactions_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sTraceStage] VARCHAR(MAX) Not NULL,
	[FKiBOID] bigint NOT NULL,
	[iHighStageID] INT NOT NULL default((0)),
	[iInstanceID] bigint NOT NULL,
	[FKiStage1ID] INT NOT NULL default((0)),
	[FKiStage2ID] INT NULL default((0)),
	[FKiStage3ID] INT NULL default((0)),
	[FKiStage4ID] INT NULL default((0)),
	[FKiStage5ID] INT NULL default((0)),
	[FKiStage6ID] INT NULL default((0)),
	[FKiStage7ID] INT NULL default((0)),
	[FKiStage8ID] INT NULL,
	[FKiStage9ID] INT NULL,
	[FKiStage10ID] INT NULL,
	[dtStage1] datetime NULL,
	[dtStage2] datetime NULL,
	[dtStage3] datetime NULL,
	[dtStage4] datetime NULL,
	[dtStage5] datetime NULL,
	[dtStage6] datetime NULL,
	[dtStage7] datetime NULL,
	[dtStage8] datetime NULL,
	[dtStage9] datetime NULL,
	[dtStage10] datetime NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[izXDeleted] INT NULL default((0)),
	[FKiAttrID] INT not NULL,
	[FKiValidTraceID] INT NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate())
)