IF OBJECT_ID('XICommunicationI_T', 'U') IS  NULL --DROP TABLE dbo.XICommunicationI_T

	
CREATE TABLE [XICommunicationI_T]
(
	[ID] INT NOT NULL,
	[XICreatedBy] VARCHAR(15) Not NULL,
	[XICreatedWhen] datetime NOT NULL,
	[XIUpdatedBy] VARCHAR(15) Not NULL,
	[XIUpdatedWhen] datetime NOT NULL,
	[XIDeleted] INT NULL,
	[sHierarchy] VARCHAR(256) NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sName] VARCHAR(256) NULL,
	[sDescription] VARCHAR(256) NULL,
	[sCode] VARCHAR(256) NULL,
	[iStatus] INT NULL,
	[iType] INT NULL,
	[iComType] INT NULL,
	[FKiComTypeID] INT NULL,
	[iDirection] INT NULL,
	[iSendStatus] INT NULL,
	[iExternalStatus] INT NULL,
	[FKiTemplateID] INT NULL,
	[XIOrigin] UNIQUEIDENTIFIER not null default(newid()),
	[XIOriginType] VARCHAR(32) NULL,
	[XIInstanceOrigin] UNIQUEIDENTIFIER not null default(newid()),
	[XIInstanceDefinition] UNIQUEIDENTIFIER NULL,
	[iRetryCount] INT NULL,
	[iRetryMax] INT NULL,
	[sFrom] VARCHAR(128) NULL,
	[sTo] VARCHAR(128) NULL,
	[sHeader] VARCHAR(512) NULL,
	[sContent] VARCHAR(MAX) NULL,
	[FKiXAttachmentsID] INT NULL,
	[sSendReceiveResult] VARCHAR(64) NULL,
	[sSendReceiveID] VARCHAR(128) NULL,
	[iRateLimit] INT NULL,
	[iInboundProcess] INT NULL,
	[sRetryLog] VARCHAR(MAX) NULL,
	[FKiTemplateIDXIGUID] UNIQUEIDENTIFIER NULL,
	[refComCategory] INT NULL,
	[sStructureCode] VARCHAR(64) NULL,
	[FKiComTypeIDXIGUID] UNIQUEIDENTIFIER NULL,
	[XIOriginID] INT NULL,
	[XIInstanceOriginID] INT NULL,
	[XIInstanceDefinitionID] INT NULL,
	[sCC] VARCHAR(1024) NULL,
	[sBCC] VARCHAR(1024) NULL,
	[FKizXDoc] VARCHAR(512) NULL,
	[sTomail] VARCHAR(512) NULL,
	[XIInstanceDefinitionIDXIGUID] UNIQUEIDENTIFIER NULL,
	[iTemplateType] VARCHAR(32) NULL,
	[sSendGridReference] NVARCHAR(2048) NULL,
	[FKiAppID] INT NULL,
	[FKiAppIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiCommunicationTypeID] INT NULL,
	[FKiCommunicationTypeIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiParentCommIID] INT NULL,
	[FKiConversationID] INT NULL,
	[iProcessStatus] INT NULL,
	[iTemplateTypeXIGUID] uniqueidentifier NULL ,
	[FKiQSInstanceID] bigint NULL,
	[FKiQSInstanceIDXIGUID] uniqueidentifier NULL,
	[sAccountOrigin] VARCHAR(256) NULL,
	[sContentPlain] VARCHAR(MAX) NULL,
	[sTemplateID] VARCHAR(128) NULL,
	[FKiOrgID] INT NULL,
	[FKiCommEMailID] INT NULL
)