IF OBJECT_ID('XINotificationSchedule_T', 'U') IS NOT NULL DROP TABLE dbo.XINotificationSchedule_T

	
CREATE TABLE [XINotificationSchedule_T]
(
	[ID] [int] IDENTITY(1,1) NOT NULL Primary key,
	[FKiNotificationID] [int] NULL,
	[FKiNotificationIDXIGUID] [uniqueidentifier] NULL,
	[sBOName] [varchar](50) NULL,
	[FKiBoid] [int] NULL,
	[sAlertType] [varchar](16) NULL,
	[sAlertMessage] [varchar](256) NULL,
	[iUserID] [int] NULL,
	[iSentMail] [int] NULL,
	[FKiBoidXIGUID] [uniqueidentifier] NULL,
	[XIGUID] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[XIDeleted] [int] NOT NULL DEFAULT ((0)),
	[XICreatedBy] [varchar](64) NOT NULL DEFAULT (''),
	[XIUpdatedBy] [varchar](64) NOT NULL DEFAULT (''),
	[XICreatedWhen] [datetime] NOT NULL DEFAULT (getdate()),
	[XIUpdatedWhen] [datetime] NOT NULL DEFAULT (getdate()),
	[iRoleID] [int] NULL,
	[iStatus] [int] NOT NULL DEFAULT ((0)),
	[dtScheduled] [datetime] NULL,
	[sName] [varchar](256) NULL,
	[sDescription] [varchar](256) NULL,
	[sCode] [varchar](256) NULL,
	[iType] [int] NULL,
	[sHierarchy] [varchar](256) NULL,
	[sSubject] nvarchar(400) NULL,
	[sNotes] nvarchar(2048) NULL,
	[bIsProcessed] bit NULL,
	[tSendWhen] nvarchar(100) NULL,
	[FKiMasterNotificationIDXIGUID] uniqueidentifier NULL,
	[FKiBODIDXIGUID] uniqueidentifier NULL,
	[FKiBOIID] int NULL,
	[FKiOrgID] int NULL,
	[dSendWhen] date NULL,
	[sTheme] nvarchar(40) NULL,
	[bIsSnoozed] bit NULL,
	[iCategory] int NULL,
	[iSendToUserID] int NULL,
	[iSendToRoleID] int NULL,
	[iSendType] int NULL
)