IF OBJECT_ID('XISignalRUsersSettings_AU_T', 'U') IS NOT NULL DROP TABLE dbo.XISignalRUsersSettings_AU_T

	
CREATE TABLE [XISignalRUsersSettings_AU_T]
(
	[ID] INT NOT NULL,
	[iUserID] INT NOT NULL,
	[sConfig] VARCHAR(32) Not NULL,
	[dtTurnOFFFrom] datetime NULL,
	[dtTurnOFFTo] datetime NULL,
	[bFlag] bit NULL,
	[iShowCount] INT NULL,
	[sConstantID] VARCHAR(64) NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[izXDeleted] INT NULL,
	[iStatus] INT NULL,
	[iNotificationBO] INT NULL,
	[fkiOneClick] INT NULL,
	[fkiBOID] INT NULL,
	[sSelectedFields] VARCHAR(MAX) NULL,
	[sWhereFields] VARCHAR(MAX) NULL,
	[FkiNewSignalrQueryID] INT NULL,
	[sOneClickOrBO] VARCHAR(16) NULL,
	[sBOSelectedFields] VARCHAR(50) NULL,
	[fkidepOneClick] INT NULL default((0)),
	[sAlertText] VARCHAR(MAX) NULL,
	[sSentMail] VARCHAR(MAX) NULL default((0)),
	[sMenu] VARCHAR(16) NULL,
	[iInstanceID] INT NULL,
	[iStructure] INT NULL,
	[sTemplate] INT NULL,
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[iRoleID] INT NULL default((0)),
	[FKiProControllerID] INT NULL,
	[FKiOrgID] INT NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[FKiAlgorithmID] INT NULL,
	[iCategory] INT NULL,
	[FKiXilinkID] INT NULL default((0)),
	[iCount] INT NULL default((0)),
	[sTag] VARCHAR(64) NULL,
	[FKiTagSpaceID] INT NULL,
	[FKiVersionID] INT NULL,
	[iNotificationBOXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiProControllerIDXIGUID] UNIQUEIDENTIFIER NULL,
	[fkiOneClickXIGUID] UNIQUEIDENTIFIER NULL,
	[fkidepOneClickXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiTagSpaceIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiVersionIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiOrgIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiBOIDXIGUID] UNIQUEIDENTIFIER NULL,
	[FKiAppID] INT NULL,
	[FKiAppIDXIGUID] UNIQUEIDENTIFIER NULL,
	[iType] INT NULL,
	[sTargetArea] VARCHAR(512) NULL,
	[FKiTemplateID] INT NULL,
	[FKiTemplateIDXIGUID] UNIQUEIDENTIFIER NULL,
	[sStructureCode] VARCHAR(64) NULL,
	[bIsSubscribed] bit NULL,
	[bShowToast] bit NULL,
	[sTheme] NVARCHAR(20) NULL,
	[bIsImportant] bit NULL
)