IF OBJECT_ID('XIDataSource_XID_T', 'U') IS NOT NULL DROP TABLE dbo.XIDataSource_XID_T

CREATE TABLE [XIDataSource_XID_T]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sType] VARCHAR(64) NULL,
	[sName] VARCHAR(64) NULL,
	[FKiOrgID] INT NULL,
	[sDescription] VARCHAR(256) NULL,
	[sConnectionString] VARCHAR(MAX) NULL,
	[FKiApplicationID] INT NOT NULL default((0)),
	[StatusTypeID] INT NULL,
	[CreatedBy] INT NOT NULL default((0)),
	[CreatedTime] datetime NOT NULL default(getdate()),
	[CreatedBySYSID] VARCHAR(512) NULL,
	[UpdatedBy] INT NOT NULL default((0)),
	[UpdatedTime] datetime NOT NULL default(getdate()),
	[UpdatedBySYSID] VARCHAR(512) NULL,
	[sQueryType] VARCHAR(128) NULL,
	[sDataSourceType] VARCHAR(128) NULL,
	[OrganisationID] INT NOT NULL default((0)),
	[zXCrtdBy] VARCHAR(15) NULL,
	[zXCrtdWhn] datetime NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[zXUpdtdWhn] datetime NULL,
	[izXDeleted] INT NOT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[sDatabase] VARCHAR(128) NULL,
	[sServer] VARCHAR(128) NULL,
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[sTag] VARCHAR(64) NULL,
	[FKiTagSpaceID] INT NULL,
	[FKiVersionID] INT NULL
)