IF OBJECT_ID('Organizations', 'U') IS NOT NULL DROP TABLE dbo.Organizations

	
CREATE TABLE [Organizations]
(
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[CreatedByID] INT NULL default((0)),
	[CreatedByName] VARCHAR(32) NULL default(''),
	[CreatedBySYSID] VARCHAR(32) NULL default(''),
	[CreatedTime] datetime NULL default('1900-01-01'),
	[ModifiedByID] INT NULL default((0)),
	[ModifiedByName] VARCHAR(32) NULL default(''),
	[ModifiedTime] datetime NULL default('1900-01-01'),
	[FKiApplicationID] INT NOT NULL default((0)),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[FKiTagSpaceID] INT NULL,
	[Email] VARCHAR(128) Not NULL,
	[zXCrtdWhn] datetime NULL,
	[NoOfUsers] INT NOT NULL,
	[DatabaseName] VARCHAR(32) NULL,
	[StatusTypeID] INT NULL,
	[bNannoApp] bit NULL,
	[PostCode] VARCHAR(128) NULL,
	[zXUpdtdBy] VARCHAR(32) NULL,
	[Password] NVARCHAR(MAX) NULL,
	[Address] VARCHAR(1024) NULL,
	[ID] INT NOT NULL,
	[izXDeleted] INT NULL,
	[Description] VARCHAR(1024) NULL,
	[zXCrtdBy] VARCHAR(32) NULL,
	[Logo] VARCHAR(1024) NULL,
	[zXUpdtdWhn] datetime NULL,
	[PhoneNumber] VARCHAR(64) NULL,
	[DatabaseType] VARCHAR(50) NULL,
	[Name] VARCHAR(128) Not NULL,
	[FKiVersionID] INT NULL,
	[ThemeID] INT NULL,
	[TypeID] INT NOT NULL,
	[Website] VARCHAR(1024) NULL,
	[sTag] VARCHAR(64) NULL,
	[FKiApplicationIDXIGUID] uniqueidentifier NULL,
	[sShortName] VARCHAR(15) NULL
)