IF OBJECT_ID('Reports', 'U') IS NOT NULL DROP TABLE dbo.Reports

	
CREATE TABLE [Reports]
(
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[OrganizationID] INT NULL default((0)),
	[CategoryID] INT NULL default((0)),
	[BOID] INT NOT NULL default((0)),
	[ParentID] INT NULL default((0)),
	[Name] VARCHAR(64) NOT NULL default(''),
	[Title] VARCHAR(64) NULL default(''),
	[TypeID] INT NULL default(''),
	[Query] VARCHAR(MAX) NULL default(''),
	[Class] INT NULL default((0)),
	[IsDynamic] bit NULL default((0)),
	[IsStoredProcedure] bit NULL default((0)),
	[SelectFields] VARCHAR(MAX) NULL default(''),
	[FromBos] VARCHAR(1024) NULL default(''),
	[WhereFields] VARCHAR(1024) NULL default(''),
	[GroupFields] VARCHAR(1024) NULL default(''),
	[OrderFields] VARCHAR(1024) NULL default(''),
	[Description] VARCHAR(1024) NULL default(''),
	[IsFilterSearch] bit NULL default((0)),
	[IsNaturalSearch] bit NULL default((0)),
	[IsParent] bit NULL default((0)),
	[IsExport] bit NULL default((0)),
	[IsRowClick] bit NULL default((0)),
	[RowXiLinkID] INT NULL default((0)),
	[IsColumnClick] bit NULL default((0)),
	[ColumnXiLinkID] INT NULL default((0)),
	[OnColumnClickValue] INT NULL default((0)),
	[IsCellClick] bit NULL default((0)),
	[CellXiLinkID] INT NULL default((0)),
	[IsRowTotal] bit NULL default((0)),
	[IsColumnTotal] bit NULL default((0)),
	[PopupLeft] INT NULL default((0)),
	[PopupTop] INT NULL default((0)),
	[PopupWidth] INT NULL default((0)),
	[PopupHeight] INT NULL default((0)),
	[IsCreate] bit NULL default((0)),
	[IsEdit] bit NULL default((0)),
	[IsDelete] bit NULL default((0)),
	[CreateRoleID] INT NULL default((0)),
	[EditRoleID] INT NULL default((0)),
	[DeleteRoleID] INT NULL default((0)),
	[CreateGroupID] INT NULL default((0)),
	[EditGroupID] INT NULL default((0)),
	[iLayoutID] INT NULL default((0)),
	[StatusTypeID] INT NULL default((0)),
	[CreatedBy] INT NULL default((0)),
	[CreatedBySYSID] VARCHAR(512) NULL default(''),
	[CreatedTime] datetime NULL default('1900-01-01'),
	[UpdatedBy] INT NULL default((0)),
	[UpdatedTime] datetime NULL default('1900-01-01'),
	[UpdatedBySYSID] VARCHAR(512) NULL,
	[ResultListDisplayType] INT NOT NULL,
	[EditableFields] VARCHAR(1024) NULL,
	[OnColumnClickType] VARCHAR(32) NULL,
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[OnCellClickType] VARCHAR(32) NULL,
	[ActionFields] VARCHAR(1024) NULL,
	[ActionFieldValue] VARCHAR(1024) NULL,
	[OnCellClickValue] INT NULL,
	[Code] VARCHAR(32) NULL,
	[NonEditableFields] VARCHAR(1024) NULL,
	[DialogAt1] VARCHAR(32) NULL,
	[SearchFields] VARCHAR(1024) NULL,
	[OnRowClickType] VARCHAR(32) NULL,
	[OnClickParameter] VARCHAR(128) NULL,
	[InnerReportID] INT NULL,
	[DialogAt2] VARCHAR(32) NULL,
	[OnClickColumn] VARCHAR(32) NULL,
	[sSystemType] VARCHAR(128) NULL,
	[OnRowClickValue] INT NULL,
	[DialogMy1] VARCHAR(32) NULL,
	[ResultIn] VARCHAR(32) NULL,
	[VisibleQuery] VARCHAR(MAX) NULL,
	[DisplayAs] INT NOT NULL,
	[DialogMy2] VARCHAR(32) NULL,
	[PopupType] VARCHAR(32) NULL,
	[ViewFields] VARCHAR(1024) NULL,
	[OnClickCell] VARCHAR(32) NULL
)