IF OBJECT_ID('XIAPPUsers_AU_T', 'U') IS NOT NULL DROP TABLE dbo.XIAPPUsers_AU_T

	
CREATE TABLE [XIAPPUsers_AU_T]
(
	[FKiApplicationID] INT NULL default((0)),
	[iReportTo] INT NULL default((0)),
	[iPaginationCount] INT NULL default((0)),
	[iInboxRefreshTime] INT NULL default((0)),
	[PhoneNumberConfirmed] bit NULL default((0)),
	[TwoFactorEnabled] bit NULL default((0)),
	[LockoutEnabled] bit NULL default((0)),
	[AccessFailedCount] INT NULL default((0)),
	[EmailConfirmed] bit NULL default((0)),
	[StatusTypeID] INT NOT NULL default((0)),
	[CreatedBy] INT NOT NULL default((0)),
	[CreatedTime] datetime NULL default(getdate()),
	[UpdatedBy] INT NOT NULL default((0)),
	[UpdatedTime] datetime NULL default(getdate()),
	[izxDeleted] INT NULL default((0)),
	[dtLastLogin] datetime NULL default(getdate()),
	[sHierarchy] VARCHAR(256) NULL default(NULL),
	[XIGUID] UNIQUEIDENTIFIER not null default(newid()),
	[XIDeleted] INT NOT NULL default((0)),
	[XICreatedBy] VARCHAR(64) NOT NULL default(''),
	[XIUpdatedBy] VARCHAR(64) NOT NULL default(''),
	[XICreatedWhen] datetime NOT NULL default(getdate()),
	[XIUpdatedWhen] datetime NOT NULL default(getdate()),
	[sLastName] NVARCHAR(MAX) NULL,
	[sRow2] NVARCHAR(128) NULL,
	[iLevel] INT NULL,
	[sPhoneNumber] VARCHAR(32) NULL,
	[sAccessCode] VARCHAR(32) NULL,
	[sRow5] NVARCHAR(128) NULL,
	[sViewHierarchy] VARCHAR(1024) NULL,
	[sMenu] NVARCHAR(MAX) NULL,
	[FKiTeamID] INT NULL,
	[zXCrtdWhn] datetime NULL,
	[sPasswordHash] VARCHAR(256) NULL,
	[sEmail] VARCHAR(128) NULL,
	[sOTP] VARCHAR(15) NULL,
	[sAppName] VARCHAR(32) NULL,
	[UpdatedBySYSID] VARCHAR(512) NULL,
	[sRow3] NVARCHAR(128) NULL,
	[FKiApplicationIDXIGUID] UNIQUEIDENTIFIER NULL,
	[CreatedBySYSID] VARCHAR(512) NULL,
	[sCol0] NVARCHAR(128) NULL,
	[sDeleteHierarchy] VARCHAR(1024) NULL,
	[FKiOrgID] INT NULL,
	[sInsertDefaultCode] VARCHAR(64) NULL,
	[sDatabaseName] VARCHAR(32) NULL,
	[sFirstName] NVARCHAR(MAX) NULL,
	[sLocation] VARCHAR(256) NULL,
	[zXUpdtdBy] VARCHAR(15) NULL,
	[UserID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[sRow1] NVARCHAR(128) NULL,
	[sTemporaryPasswordHash] VARCHAR(256) NULL,
	[sRow4] NVARCHAR(128) NULL,
	[LockoutEndDateUtc] datetime NULL,
	[sUpdateHierarchy] VARCHAR(1024) NULL,
	[zXUpdtdWhn] datetime NULL,
	[sCoreDatabaseName] VARCHAR(32) NULL,
	[zXCrtdBy] VARCHAR(15) NULL,
	[SecurityStamp] NVARCHAR(MAX) NULL,
	[sUserName] VARCHAR(128) NULL,
	[FKiRoleID] bigint NULL,
	[bDebug] bit NULL default((0)),
	[sTotpSecretKey] VARCHAR(64) NULL,
	[iLogLevel] INT NULL default((30)),
	[sShortName] VARCHAR(15) NULL
)