/****** Object:  Index [NonClusteredIndex-20240925-154104]    Script Date: 9/25/2024 3:44:16 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20240925-154104] ON [dbo].[Aggregations_T]
(
	[XIDeleted] ASC,
	[iType] ASC,
	[FKiQSInstanceIDXIGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

